# Generated by Django 4.0.4 on 2022-06-13 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0002_alter_pago_cuenta_alter_pago_estatus_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='fecha_voucher',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de voucher'),
        ),
        migrations.AddField(
            model_name='pago',
            name='importe_pagado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Importe_pagado'),
        ),
    ]
