# Generated by Django 4.0.4 on 2022-06-30 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0003_pago_fecha_voucher_pago_importe_pagado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='confirmacion_deposito',
            field=models.BooleanField(default=False, verbose_name='Confirmación depósito'),
        ),
    ]
