# Generated by Django 4.0.4 on 2022-06-30 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0004_pago_confirmacion_deposito'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='pago_realizado',
            field=models.BooleanField(default=False, verbose_name='Pago realizado'),
        ),
    ]
