# Generated by Django 4.0.4 on 2022-07-01 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0006_alter_pago_estatus_pago'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pago',
            old_name='confirmacion_deposito',
            new_name='confir_deposito',
        ),
    ]
