# Generated by Django 4.0.4 on 2022-07-01 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0007_rename_confirmacion_deposito_pago_confir_deposito'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='deposito',
            field=models.BooleanField(default=0, verbose_name='Depósito confirmado'),
        ),
    ]
