# Generated by Django 4.0.4 on 2022-07-01 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0009_remove_pago_confir_deposito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='pago_realizado',
        ),
    ]
