# Generated by Django 4.0.4 on 2022-07-01 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0010_remove_pago_pago_realizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='pagado_vencido',
            field=models.BooleanField(default=False, verbose_name='Pagado vencido'),
        ),
    ]
