# Generated by Django 4.0.4 on 2022-07-02 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0012_alter_pago_cuenta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pago',
            options={'ordering': ['id'], 'permissions': (('nuvole_estado_cuenta', 'Nuvole Mostrar estado de cuenta'), ('nuvole_listado_pagos', 'Nuvole Mostrar listado de pagos'), ('nuvole_comprobante_pagos', 'Nuvole Incluir comprobante de pago'), ('nuvole_confirma', 'Nuvole Confirma depósitos'), ('toscana_estado_cuenta', 'Toscana Mostrar estado de cuenta'), ('toscana_listado_pagos', 'Toscana Mostrar listado de pagos'), ('toscana_comprobante_pagos', 'Toscana Incluir comprobante de pago'), ('toscana_confirma', 'Toscana Confirma depósitos'), ('local_punta_o_estado_cuenta', 'Local Punta O Mostrar estado de cuenta'), ('local_punta_o_listado_pagos', 'Local Punta O Mostrar listado de pagos'), ('local_punta_o_comprobante_pagos', 'Local Punta O Incluir comprobante de pago'), ('local_punta_o_confirma', 'Local Punta O Confirma depósitos'), ('consul_punta_o_estado_cuenta', 'Consul Punta O Mostrar estado de cuenta'), ('consul_punta_o_listado_pagos', 'Consul Punta O Mostrar listado de pagos'), ('consul_punta_o_comprobante_pagos', 'Consul Punta O Incluir comprobante de pago'), ('consul_punta_o_confirma', 'Consul Punta O Confirma depósitos'), ('torre_vento_estado_cuenta', 'Torre Vento Mostrar estado de cuenta'), ('torre_ventopathe_listado_pagos', 'Torre Vento Mostrar listado de pagos'), ('torre_ventopathe_comprobante_pagos', 'Torre Vento Incluir comprobante de pago'), ('torre_ventopathe_confirma', 'Torre Vento Confirma depósitos'), ('fraccion34_pathe_estado_cuenta', 'Fracción 34 Mostrar estado de cuenta'), ('fraccion34_listado_pagos', 'Fracción 34 Mostrar listado de pagos'), ('fraccion34_comprobante_pagos', 'Fracción 34 Incluir comprobante de pago'), ('fraccion34_confirma', 'Fracción 34 Confirma depósitos'), ('vivienda_nuvole_estado_cuenta', 'Vivienda Nuvole Mostrar estado de cuenta'), ('vivienda_nuvole_listado_pagos', 'Vivienda Nuvole Mostrar listado de pagos'), ('vivienda_nuvole_comprobante_pagos', 'Vivienda Nuvole Incluir comprobante de pago'), ('vivienda_nuvole_confirma', 'Vivienda Nuvole Confirma depósitos'), ('pathe_estado_cuenta', 'Pathe Mostrar estado de cuenta'), ('pathe_listado_pagos', 'Pathe Mostrar listado de pagos'), ('pathe_comprobante_pagos', 'Pathe Incluir comprobante de pago'), ('pathe_confirma', 'Pathe Confirma depósitos'), ('condom_multiple_estado_cuenta', 'Condominio multiple Mostrar estado de cuenta'), ('condom_multiple_listado_pagos', 'Condominio multiple Mostrar listado de pagos'), ('condom_multiple_comprobante_pagos', 'Condominio multiple Incluir comprobante de pago'), ('condom_multiple_confirma', 'Condominio multiple Confirma depósitos')), 'verbose_name': 'Pagos', 'verbose_name_plural': 'Pago'},
        ),
    ]
