# Generated by Django 4.0.4 on 2022-07-03 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0016_alter_pago_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='estatus_pago',
            field=models.IntegerField(blank=True, choices=[(1, 'Vigente'), (2, 'Pagado'), (99, 'Cancelado')], default=1, null=True, verbose_name='Estatus de pago'),
        ),
    ]
