# Generated by Django 4.0.4 on 2022-07-03 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0021_alter_pago_deposito_alter_pago_pagado_vencido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='deposito',
            field=models.IntegerField(choices=[(1, 'Sin confirmar'), (2, 'Confirmado')], default=0, verbose_name='Depósito confirmado'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='forma_pago',
            field=models.IntegerField(choices=[(1, 'Cheque'), (2, 'Transferencia'), (3, 'Efectivo')], default=0, verbose_name='Estatus'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='pagado_vencido',
            field=models.IntegerField(choices=[(1, 'Normal'), (2, 'Vencido')], default=0, verbose_name='Pagado vencido'),
        ),
    ]
