# Generated by Django 4.0.4 on 2022-07-03 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0022_alter_pago_deposito_alter_pago_forma_pago_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='estatus_pago',
            field=models.IntegerField(choices=[(1, 'Vigente'), (2, 'Pagado'), (99, 'Cancelado')], default=1, verbose_name='Estatus de pago'),
        ),
    ]
