# Generated by Django 4.0.4 on 2022-07-04 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0023_alter_pago_estatus_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='paso',
            field=models.IntegerField(choices=[(1, 'Normal'), (2, 'Vencido')], default=0, verbose_name='prueba'),
        ),
    ]
