# Generated by Django 4.0.4 on 2022-07-07 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0024_pago_paso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='paso',
        ),
        migrations.AlterField(
            model_name='pago',
            name='deposito',
            field=models.IntegerField(choices=[(1, 'Sin confirmar'), (2, 'Confirmado')], default=0, verbose_name='Depósito'),
        ),
    ]
