# Generated by Django 3.2.4 on 2022-07-16 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0031_alter_pago_deposito_alter_pago_forma_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='file_comprobante',
            field=models.FileField(blank=True, default=' ', null=True, upload_to='comprobante'),
        ),
    ]
