# Generated by Django 3.2.4 on 2022-07-16 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0032_pago_file_comprobante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='foto_voucher',
        ),
    ]
