# Generated by Django 3.2.4 on 2022-08-07 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0033_remove_pago_foto_voucher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='cuenta',
            field=models.CharField(blank=True, default=' ', max_length=4, null=True, verbose_name='Número de cuenta'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='numero_comprobante',
            field=models.CharField(blank=True, default=' ', max_length=40, null=True, verbose_name='Número de comprobante'),
        ),
    ]
