# Generated by Django 4.0.4 on 2022-08-27 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0037_alter_pago_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='usuario_ins',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='usuario_mod',
        ),
        migrations.AlterField(
            model_name='pago',
            name='numero_comprobante',
            field=models.CharField(default=' ', max_length=40, verbose_name='Número de comprobante'),
        ),
    ]
