# Generated by Django 4.0.4 on 2022-09-11 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0039_alter_pago_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='folio_recibo',
            field=models.IntegerField(default=0, verbose_name='Folio de pago mensual'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='forma_pago',
            field=models.IntegerField(choices=[(0, '---------'), (1, 'Cheque'), (2, 'Transferencia'), (3, 'Efectivo')], default=0, verbose_name='Forma de pago'),
        ),
    ]
