# Generated by Django 4.0.4 on 2023-02-19 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0040_pago_folio_recibo_alter_pago_forma_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='recibo_firmado',
            field=models.FileField(blank=True, null=True, upload_to='comprobante/firmado', verbose_name='Recibo firmado mensualidad'),
        ),
    ]
