# Generated by Django 4.0.4 on 2022-06-04 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='asigna_descuento',
            field=models.BooleanField(choices=[(False, 'NO'), (True, 'Si')], default=False, verbose_name='Asigna descuento'),
        ),
    ]
