# Generated by Django 4.0.4 on 2022-06-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_alter_solicitud_asigna_descuento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='estatus_solicitud',
            field=models.IntegerField(choices=[(1, 'Nueva'), (2, 'Apartado de lote'), (3, 'Comprometida'), (4, 'Pagando a crédito'), (5, 'Reasignar'), (6, 'Terminada'), (7, 'Archivo-Terminada'), (8, 'Archivo-Cancelada'), (9, 'Contado, con datos de contrato'), (10, 'Pagando a crédito, con datos de contrato'), (11, 'Reservado'), (99, 'Cancelada')], default=1, verbose_name='Estatus'),
        ),
    ]
