# Generated by Django 4.0.4 on 2022-06-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_alter_solicitud_estatus_solicitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='tipo_descuento',
            field=models.BooleanField(choices=[(1, 'Porcentaje'), (2, 'Monto')], default=1, verbose_name='Asigna descuento'),
        ),
    ]
