# Generated by Django 4.0.4 on 2022-06-18 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_solicitud_tipo_descuento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='tipo_descuento',
            field=models.BooleanField(choices=[(0, 'Porcentaje'), (1, 'Monto')], default=1, verbose_name='Asigna descuento'),
        ),
    ]
