# Generated by Django 4.0.4 on 2022-06-18 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_alter_solicitud_tipo_descuento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='tipo_descuento',
            field=models.IntegerField(choices=[(1, 'Porcentaje'), (2, 'Monto')], default=1, verbose_name='Asigna descuento'),
        ),
    ]
