# Generated by Django 4.0.4 on 2022-06-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_alter_solicitud_tipo_descuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='foto_acta_const',
            field=models.ImageField(blank=True, default=' ', null=True, upload_to='acte_cont'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='foto_alta_shcp',
            field=models.ImageField(blank=True, default=' ', null=True, upload_to='alta_shcp'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='foto_comprobante',
            field=models.ImageField(blank=True, default=' ', null=True, upload_to='comprobante'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='foto_elector_frente',
            field=models.ImageField(blank=True, default=' ', null=True, upload_to='ine'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='foto_elector_reverso',
            field=models.ImageField(blank=True, default=' ', null=True, upload_to='ine'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='foto_matrimonio',
            field=models.ImageField(blank=True, default=' ', null=True, upload_to='matrimonio'),
        ),
    ]
