# Generated by Django 4.0.4 on 2022-06-29 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_solicitud_foto_acta_const_solicitud_foto_alta_shcp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='calle',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Calle y núm.'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='celular',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Celular'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='codpos',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Código Postal'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='colonia',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Colonia'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='correo',
            field=models.EmailField(blank=True, max_length=180, null=True, verbose_name='Correo'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='curp',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='CURP'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='estado',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Sin Estado'), (1, 'Aguascalientes'), (2, 'Baja California'), (3, 'Baja California Sur'), (4, 'Campeche'), (5, 'Coahuila'), (6, 'Colima'), (7, 'Chiapas'), (8, 'Chihuahua'), (9, 'Ciudad de México'), (10, 'Durango'), (11, 'Guanajuato'), (12, 'Guerrero'), (13, 'Hidalgo'), (14, 'Jalisco'), (15, 'México'), (16, 'Michoacán'), (17, 'Morelos'), (18, 'Nayarit'), (19, 'Nuevo León'), (20, 'Oaxaca'), (21, 'Puebla'), (22, 'Querétaro'), (23, 'Quintana Roo'), (24, 'San Luis Potosí'), (25, 'Sinaloa'), (26, 'Sonora'), (27, 'Tabasco'), (28, 'Tamaulipas'), (29, 'Tlaxcala'), (30, 'Veracruz'), (31, 'Yucatán'), (32, 'Zacatecas')], default=0, null=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='estado_civil',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Soltero'), (2, 'Casado'), (3, 'Unión libre'), (4, 'Divorciado')], null=True, verbose_name='Estado civil'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='materno',
            field=models.CharField(blank=True, default=' ', max_length=30, null=True, verbose_name='Materno'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='materno_conyuge',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Materno coyugue'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='municipio',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Municipio'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='nombre',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='nombre_conyuge',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombre coyugue'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='paterno',
            field=models.CharField(blank=True, default=' ', max_length=30, null=True, verbose_name='Paterno'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='paterno_conyuge',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Paterno coyugue'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='razon',
            field=models.CharField(blank=True, default=' ', max_length=255, verbose_name='Razón social'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='regimen',
            field=models.BooleanField(blank=True, choices=[(False, 'Bienes separados'), (True, 'Bienes mancomunados')], null=True, verbose_name='Régime'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='rfc',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='R.F.C.'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='tipo_cliente',
            field=models.BooleanField(choices=[(False, 'Persona física'), (True, 'Persona moral')], default=False, verbose_name='Tipo de cliente'),
        ),
    ]
