# Generated by Django 4.0.4 on 2022-06-30 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_solicitud_calle_solicitud_celular_solicitud_codpos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='confirmacion_apartado',
            field=models.BooleanField(default=False, verbose_name='Confirmación apartado'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='confirmacion_pago_adicional',
            field=models.BooleanField(default=False, verbose_name='Confirmación pago adicional'),
        ),
    ]
