# Generated by Django 4.0.4 on 2022-07-05 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0016_alter_solicitud_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='foto_elector_frente_cy',
            field=models.ImageField(blank=True, default=' ', null=True, upload_to='ine_cy'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='foto_elector_reverso_cy',
            field=models.ImageField(blank=True, default=' ', null=True, upload_to='ine_cy'),
        ),
    ]
