# Generated by Django 4.0.4 on 2022-07-07 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0017_solicitud_foto_elector_frente_cy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='confirmacion_apartado',
            field=models.IntegerField(choices=[(1, 'Sin confirmar'), (2, 'Confirmado')], default=0, verbose_name='Depósito'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='confirmacion_pago_adicional',
            field=models.IntegerField(choices=[(1, 'Sin confirmar'), (2, 'Confirmado')], default=0, verbose_name='Depósito'),
        ),
    ]
