# Generated by Django 4.0.4 on 2022-07-09 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0018_alter_solicitud_confirmacion_apartado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='confirmacion_apartado',
            field=models.IntegerField(choices=[(1, 'Sin confirmar'), (2, 'Confirmado')], default=1, verbose_name='Depósito'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='confirmacion_pago_adicional',
            field=models.IntegerField(choices=[(1, 'Sin confirmar'), (2, 'Confirmado')], default=1, verbose_name='Depósito'),
        ),
    ]
