# Generated by Django 4.0.4 on 2022-07-11 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0020_solicitud_foto_comprobante_apartado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='cuenta_apa',
            field=models.CharField(blank=True, default='', max_length=4, null=True, verbose_name='Número de cuenta apartado'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='cuenta_pa',
            field=models.CharField(blank=True, default='', max_length=4, null=True, verbose_name='Número de cuenta pago adic'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='forma_pago_apa',
            field=models.IntegerField(choices=[(1, 'Cheque'), (2, 'Transferencia'), (3, 'Efectivo')], default=0, verbose_name='Forma pago apartado'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='forma_pago_pa',
            field=models.IntegerField(choices=[(1, 'Cheque'), (2, 'Transferencia'), (3, 'Efectivo')], default=0, verbose_name='Forma pago pago adic.'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='numero_comprobante_apa',
            field=models.CharField(blank=True, default='', max_length=40, null=True, verbose_name='Número de comprobante apartado'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='numero_comprobante_pa',
            field=models.CharField(blank=True, default='', max_length=40, null=True, verbose_name='Número de comprobante pago adic'),
        ),
    ]
