# Generated by Django 4.0.4 on 2022-07-13 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0022_alter_solicitud_foto_comprobante_apartado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='confirmacion_apartado',
            field=models.IntegerField(blank=True, choices=[(1, 'Sin confirmar'), (2, 'Confirmado')], default=1, null=True, verbose_name='Depósito apartado'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='confirmacion_pago_adicional',
            field=models.IntegerField(blank=True, choices=[(1, 'Sin confirmar'), (2, 'Confirmado')], default=1, null=True, verbose_name='Depósito PA'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='forma_pago_apa',
            field=models.IntegerField(blank=True, choices=[(1, 'Cheque'), (2, 'Transferencia'), (3, 'Efectivo')], default=0, null=True, verbose_name='Forma pago apartado'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='forma_pago_pa',
            field=models.IntegerField(blank=True, choices=[(1, 'Cheque'), (2, 'Transferencia'), (3, 'Efectivo')], default=0, null=True, verbose_name='Forma pago pago adic.'),
        ),
    ]
