# Generated by Django 3.2.4 on 2022-07-16 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0024_alter_solicitud_confirmacion_apartado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='foto_acta_const',
            field=models.FileField(blank=True, default=' ', null=True, upload_to='acte_const'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='foto_alta_shcp',
            field=models.FileField(blank=True, default=' ', null=True, upload_to='alta_shcp'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='foto_comprobante',
            field=models.FileField(blank=True, default=' ', null=True, upload_to='comprobante'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='foto_comprobante_apartado',
            field=models.FileField(blank=True, default=' ', null=True, upload_to='compApartado'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='foto_comprobante_pago_adicional',
            field=models.FileField(blank=True, default=' ', null=True, upload_to='compAdicional'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='foto_elector_frente',
            field=models.FileField(blank=True, default=' ', null=True, upload_to='ine'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='foto_elector_frente_cy',
            field=models.FileField(blank=True, default=' ', null=True, upload_to='ine_cy'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='foto_elector_reverso',
            field=models.FileField(blank=True, default=' ', null=True, upload_to='ine'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='foto_elector_reverso_cy',
            field=models.FileField(blank=True, default=' ', null=True, upload_to='ine_cy'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='foto_matrimonio',
            field=models.FileField(blank=True, default=' ', null=True, upload_to='matrimonio'),
        ),
    ]
