# Generated by Django 3.2.4 on 2022-07-18 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0025_auto_20220716_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folios',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'Recibo pago terreno'), (2, 'Contrato'), (3, 'Comisiones'), (4, 'Facturas'), (5, 'Remisiones'), (6, 'Mensualidades')], default=1, verbose_name='Tipo folio'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='estatus_solicitud',
            field=models.IntegerField(choices=[(1, 'Nueva'), (2, 'Apartado de lote'), (3, 'Comprometida'), (4, 'Pagando a crédito'), (5, 'Reasignar'), (6, 'Terminada'), (7, 'Archivo-Terminada'), (8, 'Archivo-Cancelada'), (9, 'Contado'), (10, 'Pagando a crédito'), (99, 'Cancelada')], default=1, verbose_name='Estatus'),
        ),
    ]
