# Generated by Django 3.2.4 on 2022-07-28 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0026_auto_20220718_0242'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='fecha_confirma_pago_adicional',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha confirmado'),
        ),
    ]
