# Generated by Django 3.2.4 on 2022-08-03 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0028_solicitud_comision_pagada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folios',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'Recibo pago bienes'), (2, 'Contrato'), (3, 'Comisiones'), (4, 'Facturas'), (5, 'Remisiones'), (6, 'Mensualidades')], default=1, verbose_name='Tipo folio'),
        ),
    ]
