# Generated by Django 3.2.4 on 2022-08-08 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0029_alter_folios_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='asigna_descuento',
            field=models.IntegerField(choices=[(1, 'No'), (2, 'Si')], default=1, verbose_name='Asigna descuento'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='comision_pagada',
            field=models.IntegerField(choices=[(1, 'No'), (2, 'Si')], default=1, verbose_name='Comision pagada'),
        ),
    ]
