# Generated by Django 3.2.4 on 2022-08-18 01:44

import django.contrib.auth.mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bien', '0058_alter_lote_comision_pagada'),
        ('gestion', '0035_alter_solicitud_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reglas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modo_pago', models.IntegerField(choices=[(1, 'Contado'), (2, 'Crédito directo'), (4, 'Contado a crédito')], default=1, verbose_name='Modo de pago')),
                ('tipo_aplica_descto', models.IntegerField(choices=[(1, 'Importe de descuento por m²'), (2, '% de descuento por m2'), (3, 'Importe de descuento del precio de lista'), (4, '% de descuento de precio de lista'), (5, 'Importe descuento por cantidad de mensualidades al precio de lista'), (6, '% descuento por cantidad de mensualidades al precio de lista'), (7, 'Importe descuento por cantidad de mensualidades al precio de lista menos el enganche'), (8, '% descuento por cantidad de mensualidades al precio de lista menos el enganche')], default=0, verbose_name='Tipo aplicación descto.')),
                ('valor1', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor descto.')),
                ('tipo_apartado_minimo', models.IntegerField(choices=[(1, 'Importe minimo de apartado'), (2, 'Porcentaje del precio de lista mínimo de apartado')], default=0, verbose_name='Tipo apartado mínimo')),
                ('valor2', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor apartado')),
                ('tipo_enganche_minimo', models.IntegerField(choices=[(1, 'Importe mínimo de enganche'), (2, 'Porcentaje mínimo de enganche del precio de lista')], default=0, verbose_name='Tipo enganche mínimo')),
                ('valor3', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor enganche')),
                ('mensualidades_permitidas', models.IntegerField(default=0, verbose_name='Mensualidades permitidas')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bien.proyecto', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Regla',
                'verbose_name_plural': 'Reglas',
                'db_table': 'Regla',
                'ordering': ['proyecto', 'modo_pago', 'mensualidades_permitidas'],
                'unique_together': {('proyecto', 'modo_pago', 'mensualidades_permitidas')},
            },
            bases=(models.Model, django.contrib.auth.mixins.PermissionRequiredMixin),
        ),
    ]
