# Generated by Django 3.2.4 on 2022-08-18 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bien', '0058_alter_lote_comision_pagada'),
        ('gestion', '0036_reglas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reglas',
            new_name='Regla',
        ),
    ]
