# Generated by Django 4.0.4 on 2022-08-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0038_alter_solicitud_estado_civil'),
    ]

    operations = [
        migrations.AddField(
            model_name='regla',
            name='valor11',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor descto. terraza'),
        ),
        migrations.AlterField(
            model_name='regla',
            name='valor1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor descto. bien'),
        ),
    ]
