# Generated by Django 4.0.4 on 2022-08-27 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0040_alter_solicitud_apartado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='anio_inicio_pago',
            field=models.DecimalField(choices=[(0, '-----'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024'), (2025, '2025')], decimal_places=0, default=0, max_digits=4, verbose_name='Año de inicio de pago'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='calle',
            field=models.CharField(default=' ', max_length=250, verbose_name='Calle y núm.'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='celular',
            field=models.CharField(default=' ', max_length=10, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='codpos',
            field=models.CharField(default=' ', max_length=5, verbose_name='Código Postal'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='colonia',
            field=models.CharField(default=' ', max_length=200, verbose_name='Colonia'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='comision_pagada',
            field=models.SmallIntegerField(choices=[(0, 'No'), (1, 'Si')], default=0, verbose_name='Comision pagada'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='curp',
            field=models.CharField(default=' ', max_length=18, verbose_name='CURP'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.SmallIntegerField(choices=[(0, 'Sin Estado'), (1, 'Aguascalientes'), (2, 'Baja California'), (3, 'Baja California Sur'), (4, 'Campeche'), (5, 'Coahuila'), (6, 'Colima'), (7, 'Chiapas'), (8, 'Chihuahua'), (9, 'Ciudad de México'), (10, 'Durango'), (11, 'Guanajuato'), (12, 'Guerrero'), (13, 'Hidalgo'), (14, 'Jalisco'), (15, 'México'), (16, 'Michoacán'), (17, 'Morelos'), (18, 'Nayarit'), (19, 'Nuevo León'), (20, 'Oaxaca'), (21, 'Puebla'), (22, 'Querétaro'), (23, 'Quintana Roo'), (24, 'San Luis Potosí'), (25, 'Sinaloa'), (26, 'Sonora'), (27, 'Tabasco'), (28, 'Tamaulipas'), (29, 'Tlaxcala'), (30, 'Veracruz'), (31, 'Yucatán'), (32, 'Zacatecas')], default=0, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='foto_acta_const',
            field=models.FileField(default=' ', upload_to='acte_const'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='foto_alta_shcp',
            field=models.FileField(default=' ', upload_to='alta_shcp'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='foto_comprobante',
            field=models.FileField(default=' ', upload_to='comprobante'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='foto_elector_frente_cy',
            field=models.FileField(default=' ', upload_to='ine_cy'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='foto_elector_reverso',
            field=models.FileField(default=' ', upload_to='ine'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='foto_elector_reverso_cy',
            field=models.FileField(default=' ', upload_to='ine_cy'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='foto_matrimonio',
            field=models.FileField(default=' ', upload_to='matrimonio'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='importe_pagado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Importe pagado'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='materno',
            field=models.CharField(default=' ', max_length=30, verbose_name='Materno'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='materno_conyuge',
            field=models.CharField(default=' ', max_length=30, verbose_name='Materno coyugue'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='mes_inicio_pago',
            field=models.DecimalField(choices=[(0, '-----'), (1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], decimal_places=0, default=0, max_digits=2, verbose_name='Mes de inicio de pago'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='municipio',
            field=models.CharField(default=' ', max_length=150, verbose_name='Municipio'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='nombre',
            field=models.CharField(default=' ', max_length=30, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='nombre_conyuge',
            field=models.CharField(default=' ', max_length=30, verbose_name='Nombre coyugue'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='num_adicional',
            field=models.IntegerField(default=0, verbose_name='Recibo adicional'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='num_apartado',
            field=models.IntegerField(default=0, verbose_name='Recibo apartado'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='num_contrato',
            field=models.IntegerField(default=0, verbose_name='Número de contrato'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='pagos_pagados',
            field=models.IntegerField(default=0, verbose_name='Pagos realizados'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='paterno',
            field=models.CharField(default=' ', max_length=30, verbose_name='Paterno'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='paterno_conyuge',
            field=models.CharField(default=' ', max_length=30, verbose_name='Paterno coyugue'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='porcentaje_descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Descuento'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='razon',
            field=models.CharField(default=' ', max_length=255, verbose_name='Razón social'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='regimen',
            field=models.IntegerField(choices=[(0, 'Bienes separados'), (1, 'Bienes mancomunados')], default=0, verbose_name='Régime'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='rfc',
            field=models.CharField(default=' ', max_length=20, verbose_name='R.F.C.'),
        ),
    ]
