# Generated by Django 4.0.4 on 2022-08-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0041_alter_solicitud_anio_inicio_pago_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folios',
            name='usuario_ins',
        ),
        migrations.RemoveField(
            model_name='folios',
            name='usuario_mod',
        ),
        migrations.AlterField(
            model_name='folios',
            name='importe',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Importe recibo'),
        ),
        migrations.AlterField(
            model_name='folios',
            name='observacion',
            field=models.CharField(default=' ', max_length=200, verbose_name='Observación'),
        ),
    ]
