# Generated by Django 4.0.4 on 2022-08-28 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0042_remove_folios_usuario_ins_remove_folios_usuario_mod_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='precio_x_mt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio por m²'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Area'),
        ),
    ]
