# Generated by Django 4.0.4 on 2022-08-28 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0043_solicitud_precio_x_mt_solicitud_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='asigna_descuento',
            field=models.SmallIntegerField(choices=[(0, 'No'), (1, 'Si')], default=0, verbose_name='Asigna descuento'),
        ),
    ]
