# Generated by Django 4.0.4 on 2022-08-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0044_alter_solicitud_asigna_descuento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='tipo_cliente',
            field=models.SmallIntegerField(choices=[(0, 'Persona física'), (1, 'Persona moral')], default=0, verbose_name='Tipo de cliente'),
        ),
    ]
