# Generated by Django 4.0.4 on 2022-08-30 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0046_alter_solicitud_calle_alter_solicitud_celular_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='calle',
            field=models.CharField(default=' ', max_length=250, verbose_name='Calle y núm.'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='celular',
            field=models.CharField(default=' ', max_length=10, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='codpos',
            field=models.CharField(default=' ', max_length=5, verbose_name='Código Postal'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='colonia',
            field=models.CharField(default=' ', max_length=200, verbose_name='Colonia'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='cuenta_apa',
            field=models.CharField(default=' ', max_length=4, verbose_name='Número de cuenta apartado'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='curp',
            field=models.CharField(default=' ', max_length=18, verbose_name='CURP'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='foto_acta_const',
            field=models.FileField(default=' ', upload_to='acte_const'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='foto_alta_shcp',
            field=models.FileField(default=' ', upload_to='alta_shcp'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='foto_comprobante',
            field=models.FileField(default=' ', upload_to='comprobante'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='foto_elector_frente',
            field=models.FileField(default=' ', upload_to='ine'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='foto_elector_frente_cy',
            field=models.FileField(default=' ', upload_to='ine_cy'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='foto_elector_reverso',
            field=models.FileField(default=' ', upload_to='ine'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='foto_elector_reverso_cy',
            field=models.FileField(default=' ', upload_to='ine_cy'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='foto_matrimonio',
            field=models.FileField(default=' ', upload_to='matrimonio'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='materno',
            field=models.CharField(default=' ', max_length=30, verbose_name='Materno'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='materno_conyuge',
            field=models.CharField(default=' ', max_length=30, verbose_name='Materno coyugue'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='municipio',
            field=models.CharField(default=' ', max_length=150, verbose_name='Municipio'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='nombre',
            field=models.CharField(default=' ', max_length=30, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='nombre_conyuge',
            field=models.CharField(default=' ', max_length=30, verbose_name='Nombre coyugue'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='numero_comprobante_apa',
            field=models.CharField(default=' ', max_length=40, verbose_name='Número de comprobante apartado'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='paterno',
            field=models.CharField(default=' ', max_length=30, verbose_name='Paterno'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='paterno_conyuge',
            field=models.CharField(default=' ', max_length=30, verbose_name='Paterno coyugue'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='razon',
            field=models.CharField(default=' ', max_length=255, verbose_name='Razón social'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='rfc',
            field=models.CharField(default=' ', max_length=20, verbose_name='R.F.C.'),
        ),
    ]
