# Generated by Django 4.0.4 on 2022-08-30 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0047_alter_solicitud_calle_alter_solicitud_celular_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='correo',
            field=models.EmailField(default=' ', max_length=180, verbose_name='Correo'),
        ),
    ]
