# Generated by Django 4.0.4 on 2022-09-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0048_alter_solicitud_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='correo',
            field=models.CharField(default=' ', max_length=180, verbose_name='Correo'),
        ),
    ]
