# Generated by Django 4.0.4 on 2023-02-18 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0053_alter_solicitud_cantidad_pagos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='anio_inicio_pago',
            field=models.DecimalField(choices=[(0, '-----'), (2017, '2017'), (2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024'), (2025, '2025')], decimal_places=0, default=0, max_digits=4, verbose_name='Año de inicio de pago'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='estatus_solicitud',
            field=models.IntegerField(choices=[(1, 'Nueva'), (2, 'Apartado de lote'), (3, 'Comprometida'), (4, 'Pagando a crédito'), (5, 'Reasignar'), (6, 'Terminada'), (7, 'Archivo-Terminada'), (8, 'Archivo-Cancelada'), (9, 'Terminada'), (10, 'Pagando a crédito'), (99, 'Cancelada')], default=1, verbose_name='Estatus'),
        ),
    ]
