# Generated by Django 4.0.4 on 2023-02-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0055_solicitud_recibo_firmado_apa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='foto_comprobante_apartado',
            field=models.FileField(blank=True, null=True, upload_to='compApartado', verbose_name='Comprobante cliente apartado'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='foto_comprobante_pago_adicional',
            field=models.FileField(blank=True, null=True, upload_to='compAdicional', verbose_name='Comprobante cliente pago adicional'),
        ),
    ]
