# Generated by Django 4.0.4 on 2023-03-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0056_alter_solicitud_foto_comprobante_apartado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='estatus_solicitud',
            field=models.IntegerField(choices=[(1, 'Nueva'), (2, 'Apartado de lote'), (3, 'Comprometida'), (4, 'Pagando a crédito'), (5, 'Reasignar'), (6, 'Terminada'), (7, 'Terminada'), (8, 'Cancelada'), (9, 'Terminada'), (10, 'Pagando a crédito'), (99, 'Cancelada')], default=1, verbose_name='Estatus'),
        ),
    ]
