# Generated by Django 4.0.4 on 2023-04-18 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0057_alter_solicitud_estatus_solicitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regla',
            name='tipo_aplica_descto',
            field=models.IntegerField(choices=[(1, 'Importe de descuento por m²'), (2, '% de descuento por m2'), (3, 'Importe de descuento del precio de lista'), (4, '% de descuento de precio de lista')], default=0, verbose_name='Tipo aplicación descto.'),
        ),
    ]
