# Generated by Django 4.0.4 on 2023-05-07 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0058_alter_regla_tipo_aplica_descto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='precio_lote',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Precio lote'),
        ),
    ]
