# Generated by Django 4.0.4 on 2023-05-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0059_alter_solicitud_precio_lote'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='credito',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Crédito'),
        ),
    ]
