# Generated by Django 4.0.4 on 2023-07-06 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0061_alter_solicitud_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regla',
            name='valor1',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=17, verbose_name='Valor descto. bien'),
        ),
    ]
