# Generated by Django 4.0.4 on 2023-07-18 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bien', '0085_alter_proyecto_tipo_proyecto'),
        ('gestion', '0062_alter_regla_valor1'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='regla',
            unique_together={('proyecto', 'modo_pago', 'valor1', 'mensualidades_permitidas')},
        ),
    ]
