# Generated by Django 4.0.4 on 2022-05-31 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleado', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banco',
            name='usuario_ins',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bn_user_ins', to='empleado.empleado', verbose_name='Usuario insertó'),
        ),
        migrations.AddField(
            model_name='banco',
            name='usuario_mod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bn_user_mod', to='empleado.empleado', verbose_name='Usuario modificó'),
        ),
        migrations.AlterUniqueTogether(
            name='banco',
            unique_together={('banco',)},
        ),
    ]
