# Generated by Django 4.0.4 on 2022-08-27 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banco',
            name='usuario_ins',
        ),
        migrations.RemoveField(
            model_name='banco',
            name='usuario_mod',
        ),
        migrations.AlterField(
            model_name='titulo',
            name='domicilio2',
            field=models.CharField(default=' ', max_length=80, verbose_name='Domicilio renglon 2'),
        ),
        migrations.AlterField(
            model_name='titulo',
            name='domicilio3',
            field=models.CharField(default=' ', max_length=80, verbose_name='Domicilio renglon 3'),
        ),
        migrations.AlterField(
            model_name='titulo',
            name='telefono',
            field=models.CharField(default=' ', max_length=100, verbose_name='Teléfono'),
        ),
    ]
