# Generated by Django 4.0.4 on 2022-06-11 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='paterno',
            field=models.CharField(blank=True, default=' ', max_length=30, null=True, verbose_name='Paterno'),
        ),
    ]
