# Generated by Django 4.0.4 on 2022-06-25 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_alter_cliente_paterno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='telefono_fijo',
        ),
        migrations.AddField(
            model_name='cliente',
            name='razon',
            field=models.CharField(blank=True, default=' ', max_length=255, verbose_name='Razón social'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='regimen',
            field=models.BooleanField(blank=True, choices=[(False, 'Bienes separados'), (True, 'Bienes mancomunados')], null=True, verbose_name='Régime'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_cliente',
            field=models.BooleanField(choices=[(False, 'Persona física'), (True, 'Persona moral')], default=False, verbose_name='Tipo de cliente'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('E', 'Empresa')], default='M', max_length=1, verbose_name='Género'),
        ),
    ]
