# Generated by Django 3.2.4 on 2022-08-22 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0006_alter_cliente_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='estado_civil',
            field=models.SmallIntegerField(choices=[(1, 'Soltero'), (2, 'Casado'), (3, 'Unión libre'), (4, 'Divorciado')], default=1, verbose_name='Estado civil'),
        ),
    ]
