# Generated by Django 4.0.4 on 2022-08-27 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0007_alter_cliente_estado_civil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='usuario_ins',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='usuario_mod',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='calle',
            field=models.CharField(default=' ', max_length=250, verbose_name='Calle y núm.'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='celular',
            field=models.CharField(default=' ', max_length=10, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='codpos',
            field=models.CharField(default=' ', max_length=5, verbose_name='Código Postal'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='colonia',
            field=models.CharField(default=' ', max_length=200, verbose_name='Colonia'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='curp',
            field=models.CharField(default=' ', max_length=18, verbose_name='CURP'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='estado',
            field=models.SmallIntegerField(choices=[(0, 'Sin Estado'), (1, 'Aguascalientes'), (2, 'Baja California'), (3, 'Baja California Sur'), (4, 'Campeche'), (5, 'Coahuila'), (6, 'Colima'), (7, 'Chiapas'), (8, 'Chihuahua'), (9, 'Ciudad de México'), (10, 'Durango'), (11, 'Guanajuato'), (12, 'Guerrero'), (13, 'Hidalgo'), (14, 'Jalisco'), (15, 'México'), (16, 'Michoacán'), (17, 'Morelos'), (18, 'Nayarit'), (19, 'Nuevo León'), (20, 'Oaxaca'), (21, 'Puebla'), (22, 'Querétaro'), (23, 'Quintana Roo'), (24, 'San Luis Potosí'), (25, 'Sinaloa'), (26, 'Sonora'), (27, 'Tabasco'), (28, 'Tamaulipas'), (29, 'Tlaxcala'), (30, 'Veracruz'), (31, 'Yucatán'), (32, 'Zacatecas')], default=0, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='materno',
            field=models.CharField(default=' ', max_length=30, verbose_name='Materno'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='materno_conyuge',
            field=models.CharField(default=' ', max_length=30, verbose_name='Materno coyugue'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='municipio',
            field=models.CharField(default=' ', max_length=150, verbose_name='Municipio'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(default=' ', max_length=30, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre_conyuge',
            field=models.CharField(default=' ', max_length=30, verbose_name='Nombre coyugue'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='paterno',
            field=models.CharField(default=' ', max_length=30, verbose_name='Paterno'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='paterno_conyuge',
            field=models.CharField(default=' ', max_length=30, verbose_name='Paterno coyugue'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='regimen',
            field=models.BooleanField(choices=[(0, 'Bienes separados'), (1, 'Bienes mancomunados')], default=0, verbose_name='Régime'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rfc',
            field=models.CharField(default=' ', max_length=20, verbose_name='R.F.C.'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_cliente',
            field=models.IntegerField(choices=[(0, 'Persona física'), (1, 'Persona moral')], default=0, verbose_name='Tipo de cliente'),
        ),
    ]
