# Generated by Django 4.0.4 on 2022-10-04 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0010_alter_cliente_celular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='calle',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Calle y núm.'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='celular',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='codpos',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Código Postal'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='colonia',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Colonia'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='curp',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='CURP'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='materno',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Materno'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='materno_conyuge',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Materno coyugue'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='municipio',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Municipio'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre_conyuge',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombre coyugue'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='paterno',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Paterno'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='paterno_conyuge',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Paterno coyugue'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='razon',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Razón social'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rfc',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='R.F.C.'),
        ),
    ]
