# Generated by Django 4.0.4 on 2022-05-31 20:59

import django.contrib.auth.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Esquema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_plano', models.CharField(max_length=100, verbose_name='Nombre del plano')),
                ('esquema', models.ImageField(upload_to='planos', verbose_name='Plano')),
                ('estatus_plano', models.IntegerField(choices=[(1, 'Activo'), (2, 'Baja')], default=1, verbose_name='Estatus plano')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
                'db_table': 'Plano',
                'ordering': ['proyecto', 'nombre_plano'],
            },
            bases=(models.Model, django.contrib.auth.mixins.PermissionRequiredMixin),
        ),
        migrations.CreateModel(
            name='Estacionamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, verbose_name='lugar')),
                ('frente', models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True, verbose_name='frente')),
                ('fondo', models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True, verbose_name='fondo')),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True, verbose_name='total')),
                ('compartido', models.BooleanField(choices=[(False, 'NO'), (True, 'Si')], default=False, verbose_name='Compartido')),
                ('estatus_estaciona', models.IntegerField(choices=[(1, 'Activo'), (2, 'Baja')], default=1, verbose_name='Estatus estacionamiento')),
                ('coordenadas', models.CharField(blank=True, max_length=255, null=True, verbose_name='Coordenas')),
                ('posicion_x', models.IntegerField(blank=True, null=True, verbose_name='Posición X numero')),
                ('posicion_y', models.IntegerField(blank=True, null=True, verbose_name='Posición Y numero')),
                ('posicion_texto_x', models.IntegerField(blank=True, null=True, verbose_name='Posición X mts')),
                ('posicion_texto_y', models.IntegerField(blank=True, null=True, verbose_name='Posición Y mts')),
                ('posicion_circulo_x', models.IntegerField(blank=True, null=True, verbose_name='Posición X circulo')),
                ('posicion_circulo_y', models.IntegerField(blank=True, null=True, verbose_name='Posición Y circulo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Estacionamiento',
                'verbose_name_plural': 'Estacionamientos',
                'db_table': 'estacionamiento',
                'ordering': ['lote', 'numero'],
            },
            bases=(models.Model, django.contrib.auth.mixins.PermissionRequiredMixin),
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase', models.SmallIntegerField(blank=True, choices=[(1, 'Uno'), (2, 'Dos'), (3, 'Tres')], default=1, null=True, verbose_name='Fase')),
                ('manzana', models.SmallIntegerField(blank=True, null=True, verbose_name='Manzana')),
                ('nivel', models.SmallIntegerField(blank=True, null=True, verbose_name='Nivel')),
                ('lote', models.CharField(max_length=10, verbose_name='Lote')),
                ('tipo_lote', models.BooleanField(blank=True, default=True, null=True, verbose_name='Tipo de lote')),
                ('obs_irregular', models.CharField(blank=True, max_length=250, null=True, verbose_name='Medidas')),
                ('fondo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Fondo')),
                ('frente', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Frente')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total m²')),
                ('esquina', models.BooleanField(blank=True, choices=[(False, ''), (True, 'Si')], default=False, null=True, verbose_name='Esquina')),
                ('precio_x_mt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio por m²')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('colindancia_norte', models.CharField(blank=True, max_length=250, null=True, verbose_name='Colindancia norte')),
                ('colindancia_sur', models.CharField(blank=True, max_length=250, null=True, verbose_name='Colindancia sur')),
                ('colindancia_este', models.CharField(blank=True, max_length=250, null=True, verbose_name='Colindancia este')),
                ('colindancia_oeste', models.CharField(blank=True, max_length=250, null=True, verbose_name='Colindancia oeste')),
                ('terraza', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Terraza m²')),
                ('precio_x_mt_t', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio por m² terraza')),
                ('precio_terraza', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio terraza')),
                ('altura', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Altura')),
                ('estatus_lote', models.IntegerField(choices=[(1, 'Disponible'), (2, 'Apartado'), (3, 'Vendido'), (4, 'Reservado')], default=1, verbose_name='Estatus')),
                ('coordenadas', models.CharField(blank=True, max_length=255, null=True, verbose_name='Coordenas')),
                ('posicion_x', models.IntegerField(blank=True, null=True, verbose_name='Posición X numero')),
                ('posicion_y', models.IntegerField(blank=True, null=True, verbose_name='Posición Y numero')),
                ('posicion_texto_x', models.IntegerField(blank=True, null=True, verbose_name='Posición X mts')),
                ('posicion_texto_y', models.IntegerField(blank=True, null=True, verbose_name='Posición Y mts')),
                ('posicion_circulo_x', models.IntegerField(blank=True, null=True, verbose_name='Posición X circulo')),
                ('posicion_circulo_y', models.IntegerField(blank=True, null=True, verbose_name='Posición Y circulo')),
                ('estacionamientos', models.IntegerField(blank=True, null=True, verbose_name='Estacionamientos')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
                'db_table': 'Lote',
                'ordering': ['proyecto', 'lote'],
            },
            bases=(models.Model, django.contrib.auth.mixins.PermissionRequiredMixin),
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_proyecto', models.IntegerField(choices=[(1, 'Lotes'), (2, 'Locales comerciales'), (3, 'Vivienda horizontal'), (4, 'Vivienda vertical'), (5, 'Consultorios')], default=1, verbose_name='Tipo de proyecto')),
                ('nombre', models.CharField(max_length=60, verbose_name='Nombre proyecto')),
                ('ubicacion', models.CharField(max_length=250, verbose_name='Ubicación')),
                ('estado', models.IntegerField(choices=[(0, 'Sin Estado'), (1, 'Aguascalientes'), (2, 'Baja California'), (3, 'Baja California Sur'), (4, 'Campeche'), (5, 'Coahuila'), (6, 'Colima'), (7, 'Chiapas'), (8, 'Chihuahua'), (9, 'Ciudad de México'), (10, 'Durango'), (11, 'Guanajuato'), (12, 'Guerrero'), (13, 'Hidalgo'), (14, 'Jalisco'), (15, 'México'), (16, 'Michoacán'), (17, 'Morelos'), (18, 'Nayarit'), (19, 'Nuevo León'), (20, 'Oaxaca'), (21, 'Puebla'), (22, 'Querétaro'), (23, 'Quintana Roo'), (24, 'San Luis Potosí'), (25, 'Sinaloa'), (26, 'Sonora'), (27, 'Tabasco'), (28, 'Tamaulipas'), (29, 'Tlaxcala'), (30, 'Veracruz'), (31, 'Yucatán'), (32, 'Zacatecas')], default=0, verbose_name='Estado')),
                ('precio_apartir', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio a partir')),
                ('plano', models.ImageField(blank=True, null=True, upload_to='proyecto')),
                ('estatus_proyecto', models.IntegerField(choices=[(1, 'Activo'), (2, 'Baja')], default=1, verbose_name='Activo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('app', models.CharField(blank=True, max_length=20, null=True, verbose_name='App')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'db_table': 'Proyecto',
                'ordering': ['id'],
                'permissions': (('proyecto_nuvole', 'Acceso al proyecto nuvole lotes'), ('proyecto_toscana', 'Acceso al proyecto toscana local comercial')),
            },
        ),
    ]
