# Generated by Django 4.0.4 on 2022-06-02 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bien', '0003_alter_proyecto_tipo_proyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio'),
        ),
    ]
