# Generated by Django 4.0.4 on 2022-06-02 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bien', '0005_alter_lote_esquina_alter_lote_tipo_lote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='tipo_lote',
            field=models.BooleanField(choices=[(True, 'Regular'), (False, 'Irregular')], default=1, verbose_name='Tipo de lote'),
        ),
    ]
