# Generated by Django 4.0.4 on 2022-06-03 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bien', '0008_lote_gran_total'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lote',
            unique_together={('proyecto', 'fase', 'manzana', 'lote'), ('proyecto', 'lote')},
        ),
    ]
