# Generated by Django 4.0.4 on 2022-06-05 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bien', '0009_alter_lote_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='tipo_lote',
            field=models.BooleanField(blank=True, choices=[(True, 'Regular'), (False, 'Irregular')], default=1, null=True, verbose_name='Tipo de lote'),
        ),
    ]
