# Generated by Django 4.0.4 on 2022-06-05 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bien', '0010_alter_lote_tipo_lote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='esquina',
            field=models.BooleanField(blank=True, choices=[(False, 'No'), (True, 'Si')], default=0, null=True, verbose_name='Esquina'),
        ),
    ]
