# Generated by Django 4.0.4 on 2022-06-05 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bien', '0011_alter_lote_esquina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='altura',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Altura'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='estacionamientos',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Estacionamientos'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='precio_terraza',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Precio terraza'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='precio_x_mt_t',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Precio por m² terraza'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='terraza',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Terraza m²'),
        ),
    ]
