# Generated by Django 4.0.4 on 2022-06-05 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bien', '0012_alter_lote_altura_alter_lote_estacionamientos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='gran_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Total gral.'),
        ),
    ]
