# Generated by Django 4.0.4 on 2022-06-06 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bien', '0013_alter_lote_gran_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacionamiento',
            name='compartido',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Si')], default=False, verbose_name='Compartido'),
        ),
    ]
