# Generated by Django 4.0.4 on 2022-06-13 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bien', '0014_alter_estacionamiento_compartido'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lote',
            options={'ordering': ['proyecto', 'lote'], 'permissions': (('reservar', 'Reservar bien'),), 'verbose_name': 'Lote', 'verbose_name_plural': 'Lotes'},
        ),
    ]
