# Generated by Django 4.0.4 on 2022-06-29 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bien', '0015_alter_lote_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto',
            options={'ordering': ['id'], 'permissions': (('proyecto_nuvole', 'Acceso al proyecto nuvole lotes'), ('proyecto_toscana', 'Acceso al proyecto toscana local comercial'), ('proyecto_localOriente', 'Acceso al proyecto locales punta oriente'), ('proyecto_consultorioOriente', 'Acceso al proyecto consultorios punta oriente'), ('proyecto_torresVento', 'Acceso al proyecto torres vento')), 'verbose_name': 'Proyecto', 'verbose_name_plural': 'Proyectos'},
        ),
    ]
