# Generated by Django 4.0.4 on 2022-06-29 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bien', '0016_alter_proyecto_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto',
            options={'ordering': ['id'], 'permissions': (('proyecto_nuvole', 'Acceso al proyecto nuvole lotes'), ('proyecto_toscana', 'Acceso al proyecto toscana local comercial'), ('proyecto_localOriente', 'Acceso al proyecto locales punta oriente'), ('proyecto_consultorioOriente', 'Acceso al proyecto consultorios punta oriente'), ('proyecto_torresVento', 'Acceso al proyecto torres vento'), ('proyecto_condominioMultiple', 'Acceso al proyecto condominio múltiple'), ('proyecto_fraccion34', 'Acceso al proyecto fracción 34'), ('proyecto_viviendaNuvole', 'Acceso al proyecto vivienda nuvole'), ('proyecto_pathe', 'Acceso al proyecto pathe')), 'verbose_name': 'Proyecto', 'verbose_name_plural': 'Proyectos'},
        ),
    ]
