# Generated by Django 4.0.4 on 2022-06-29 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bien', '0019_alter_proyecto_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto',
            options={'ordering': ['id'], 'permissions': (('nuvole', 'Acceso al proyecto nuvole lotes'), ('toscana', 'Acceso al proyecto toscana local comercial'), ('localOriente', 'Acceso al proyecto locales punta oriente'), ('consultorioOriente', 'Acceso al proyecto consultorios punta oriente'), ('torresVento', 'Acceso al proyecto torres vento'), ('condominioMultiple', 'Acceso al proyecto condominio múltiple'), ('fraccion34', 'Acceso al proyecto fracción 34'), ('viviendaNuvole', 'Acceso al proyecto vivienda nuvole'), ('pathe', 'Acceso al proyecto pathe')), 'verbose_name': 'Proyecto', 'verbose_name_plural': 'Proyectos'},
        ),
    ]
