# Generated by Django 4.0.4 on 2022-06-29 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bien', '0020_alter_proyecto_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto',
            options={'ordering': ['id'], 'permissions': (('nuvole', 'Acceso al proyecto nuvole lotes'), ('toscana', 'Acceso al proyecto toscana local comercial'), ('local_oriente', 'Acceso al proyecto locales punta oriente'), ('consultor_oriente', 'Acceso al proyecto consultorios punta oriente'), ('torres_vento', 'Acceso al proyecto torres vento'), ('condominio_multiple', 'Acceso al proyecto condominio múltiple'), ('fraccion34', 'Acceso al proyecto fracción 34'), ('vivienda_nuvole', 'Acceso al proyecto vivienda nuvole'), ('pathe', 'Acceso al proyecto pathe')), 'verbose_name': 'Proyecto', 'verbose_name_plural': 'Proyectos'},
        ),
    ]
