# Generated by Django 4.0.4 on 2022-06-29 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bien', '0021_alter_proyecto_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lote',
            options={'ordering': ['proyecto', 'lote'], 'permissions': (('reservar_nuvole', 'Reservar bien nuvole'), ('reservar_toscana', 'Reservar bien toscana'), ('reservar_local_punta_oriente', 'Reservar bien local punta oriente'), ('reservar_consul_punta_oriente', 'Reservar bien consultorio punta oriente'), ('reservar_torre_vento', 'Reservar bien torre vento'), ('reservar_fraccion34', 'Reservar bien fracción 34'), ('reservar_vivienda_nuvole', 'Reservar bien vivienda nuvole'), ('reservar_pathe', 'Reservar bien pathe'), ('reservar_condom_multiple', 'Reservar bien condominio multiple'), ('ver_toscana', 'Visualizar locales toscana'), ('ver_local_punta', 'Visualizar locales punta oriente'), ('ver_consul_punta', 'Visualizar consultorios punta oriente'), ('ver_torre_vento', 'Visualizar condominios vento'), ('ver_fraccion34', 'Visualizar fracción 34'), ('ver_vivienda_nuvole', 'Visualizar viviendas nuvole'), ('ver_pathe', 'Visualizar vivienda horizontal'), ('ver_condom_multiple', 'Visualizar condominio múltiple'), ('add_toscana', 'Agregar locales toscana'), ('add_local_punta', 'Agregar locales punta oriente'), ('add_consul_punta', 'Agregar consultorios punta oriente'), ('add_torre_vento', 'Agregar condominios vento'), ('add_fraccion34', 'Agregar fracción 34'), ('add_vivienda_nuvole', 'Agregar viviendas nuvole'), ('add_pathe', 'Agregar vivienda horizontal'), ('add_condom_multiple', 'Agregar condominio múltiple'), ('chag_toscana', 'Cambiar locales toscana'), ('chag_local_punta', 'Cambiar locales punta oriente'), ('chag_consul_punta', 'Cambiar consultorios punta oriente'), ('chag_torre_vento', 'Cambiar condominios vento'), ('chag_fraccion34', 'Cambiar fracción 34'), ('chag_vivienda_nuvole', 'Cambiar viviendas nuvole'), ('chag_pathe', 'Cambiar vivienda horizontal'), ('chag_condom_multiple', 'Cambiar condominio múltiple')), 'verbose_name': 'Lote', 'verbose_name_plural': 'Lotes'},
        ),
        migrations.AddField(
            model_name='proyecto',
            name='singular',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Proyecto en sigular'),
        ),
    ]
