# Generated by Django 4.0.4 on 2022-07-02 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bien', '0022_alter_lote_options_proyecto_singular'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lote',
            options={'ordering': ['proyecto', 'lote'], 'permissions': (('nuvole_ver', 'Nuvole Visualizar locales'), ('nuvole_add', 'Nuvole Agregar locales'), ('nuvole_chag', 'Nuvole Cambiar locales'), ('nuvole_reservar', 'Nuvole Reservar bien'), ('toscana_ver', 'Toscana Visualizar locales'), ('toscana_add', 'Toscana Agregar locales'), ('toscana_chag', 'Toscana Cambiar locales'), ('toscana_reservar', 'Toscana Reservar bien'), ('local_punta_o_ver', 'Local Punta O Visualizar'), ('local_punta_o_add', 'Local Punta O Agregar'), ('local_punta_o_chag', 'Local Punta O Cambiar'), ('local_punta_o_reservar', 'Local Punta O Reservar bien'), ('consul_punta_o_ver', 'Consul Punta O Visualizar'), ('consul_punta_o_add', 'Consul Punta O Agregar'), ('consul_punta_o_chag', 'Consul Punta O Cambiar'), ('consul_punta_o_reservar', 'Consul Punta O Reservar bien'), ('torre_vento_ver', 'Torre Vento Visualizar'), ('torre_vento_add', 'Torre Vento Agregar'), ('torre_vento_chag', 'Torre Vento Cambiar'), ('torre_vento_reservar', 'Torre Vento Reservar bien'), ('fraccion34_ver', 'Fracción 34 Visualizar'), ('fraccion34_add', 'Fracción 34 Agregar'), ('fraccion34_chag', 'Fracción 34 Cambiar'), ('fraccion34_reservar', 'Fracción 34 Reservar bien'), ('vivienda_nuvole_ver', 'Vivienda Nuvole Visualizar'), ('vivienda_nuvole_add', 'Vivienda Nuvole Agregar'), ('vivienda_nuvole_chag', 'Vivienda Nuvole Cambiar'), ('vivienda_nuvole_reservar', 'Vivienda Nuvole Reservar bien'), ('pathe_ver', 'Pathe Visualizar'), ('pathe_add', 'Pathe Agregar'), ('pathe_chag', 'Pathe Cambiar'), ('pathe_reservar', 'Pathe Reservar bien'), ('condom_multiple_ver', 'Visualizar condominio múltiple'), ('condom_multiple_add', 'Agregar condominio múltiple'), ('condom_multiple_chag', 'Cambiar condominio múltiple'), ('condom_multiple_reservar', 'Reservar bien condominio multiple')), 'verbose_name': 'Lote', 'verbose_name_plural': 'Lotes'},
        ),
    ]
