# Generated by Django 4.0.4 on 2022-07-02 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bien', '0023_alter_lote_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto',
            options={'ordering': ['id'], 'permissions': (('nuvole_acceso', 'Nuvole Acceso'), ('toscana_acceso', 'Toscana Acceso'), ('local_punta_o_acceso', 'Local Punta O Acceso'), ('consul_punta_o_acceso', 'Consul Punta O Acceso'), ('torres_vento_acceso', 'Torres Vento Acceso'), ('fraccion34_acceso', 'Fracción 34 Acceso'), ('vivienda_nuvole_acceso', 'Vivienda Nuvole Acceso'), ('pathe_acceso', 'Pathe Acceso'), ('condom_multiple_acceso', 'Condominio Multiple Acceso')), 'verbose_name': 'Proyecto', 'verbose_name_plural': 'Proyectos'},
        ),
    ]
