# Generated by Django 4.0.4 on 2022-07-02 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bien', '0025_alter_lote_options_alter_proyecto_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lote',
            options={'ordering': ['proyecto', 'lote'], 'permissions': (('nuvole_ver', 'Nuvole Visualizar locales'), ('nuvole_add', 'Nuvole Agregar locales'), ('nuvole_chag', 'Nuvole Cambiar locales'), ('nuvole_reservar', 'Nuvole Reservar bien'), ('toscana_ver', 'Toscana Visualizar locales'), ('toscana_add', 'Toscana Agregar locales'), ('toscana_chag', 'Toscana Cambiar locales'), ('toscana_reservar', 'Toscana Reservar bien'), ('local_punta_o_ver', 'Local Punta O Visualizar'), ('local_punta_o_add', 'Local Punta O Agregar'), ('local_punta_o_chag', 'Local Punta O Cambiar'), ('local_punta_o_reservar', 'Local Punta O Reservar bien'), ('consul_punta_o_ver', 'Consultorio Punta O Visualizar'), ('consul_punta_o_add', 'Consultorio Punta O Agregar'), ('consul_punta_o_chag', 'Consultorio Punta O Cambiar'), ('consul_punta_o_reservar', 'Consultorio Punta O Reservar bien'), ('torre_vento_ver', 'Torre Vento Visualizar'), ('torre_vento_add', 'Torre Vento Agregar'), ('torre_vento_chag', 'Torre Vento Cambiar'), ('torre_vento_reservar', 'Torre Vento Reservar bien'), ('fraccion34_ver', 'Fracción 34 Visualizar'), ('fraccion34_add', 'Fracción 34 Agregar'), ('fraccion34_chag', 'Fracción 34 Cambiar'), ('fraccion34_reservar', 'Fracción 34 Reservar bien'), ('vivienda_nuvole_ver', 'Vivienda Nuvole Visualizar'), ('vivienda_nuvole_add', 'Vivienda Nuvole Agregar'), ('vivienda_nuvole_chag', 'Vivienda Nuvole Cambiar'), ('vivienda_nuvole_reservar', 'Vivienda Nuvole Reservar bien'), ('pathe_ver', 'Pathe Visualizar'), ('pathe_add', 'Pathe Agregar'), ('pathe_chag', 'Pathe Cambiar'), ('pathe_reservar', 'Pathe Reservar bien'), ('condom_multiple_ver', 'Condominio Múltiple Visualizar'), ('condom_multiple_add', 'Condominio Múltiple Agregar'), ('condom_multiple_chag', 'Condominio Múltiple Cambiar'), ('condom_multiple_reservar', 'Condominio Múltiple Reservar')), 'verbose_name': 'Lote', 'verbose_name_plural': 'Lotes'},
        ),
        migrations.AlterModelOptions(
            name='proyecto',
            options={'ordering': ['id'], 'permissions': (('nuvole_acceso', 'Nuvole Acceso'), ('toscana_acceso', 'Toscana Acceso'), ('local_punta_o_acceso', 'Local Punta O Acceso'), ('consul_punta_o_acceso', 'Consultorio Punta O Acceso'), ('torre_vento_acceso', 'Torre Vento Acceso'), ('fraccion34_acceso', 'Fracción 34 Acceso'), ('vivienda_nuvole_acceso', 'Vivienda Nuvole Acceso'), ('pathe_acceso', 'Pathe Acceso'), ('condom_multiple_acceso', 'Condominio Múltiple Acceso')), 'verbose_name': 'Proyecto', 'verbose_name_plural': 'Proyectos'},
        ),
    ]
