# Generated by Django 4.0.4 on 2022-07-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bien', '0026_alter_lote_options_alter_proyecto_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='nom_proy',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='App'),
        ),
    ]
