# Generated by Django 4.0.4 on 2022-07-03 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bien', '0027_proyecto_nom_proy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='nom_proy',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Abrev Proyecto'),
        ),
    ]
