# Generated by Django 3.2.4 on 2022-07-21 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bien', '0030_alter_lote_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='bien_anexo',
            field=models.IntegerField(default=0, verbose_name='Anexo bien'),
        ),
        migrations.AddField(
            model_name='lote',
            name='gpo_lote',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Grupo de bienes'),
        ),
    ]
