# Generated by Django 3.2.4 on 2022-07-22 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bien', '0031_auto_20220721_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='reciente',
            field=models.IntegerField(default=0, verbose_name='Ultimos lotes'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='gpo_lote',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Grupo de bienes'),
        ),
    ]
