# Generated by Django 3.2.4 on 2022-07-29 18:08

import django.contrib.auth.mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0002_alter_empleado_asigna_solicitud'),
        ('bien', '0034_lote_comision_pagada'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComisionAgente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comsion', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Comisión')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('empleado_com', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Empleado_com_age', to='empleado.empleado')),
                ('proyecto_com', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Proyecto_com_age', to='bien.proyecto')),
            ],
            options={
                'verbose_name': 'Comisión por asesor',
                'verbose_name_plural': 'Comisiones',
                'db_table': 'ComisionAgente',
                'ordering': ['empleado_com', 'proyecto_com'],
                'unique_together': {('proyecto_com', 'empleado_com')},
            },
            bases=(models.Model, django.contrib.auth.mixins.PermissionRequiredMixin),
        ),
    ]
