# Generated by Django 3.2.4 on 2022-07-29 18:10

import django.contrib.auth.mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0002_alter_empleado_asigna_solicitud'),
        ('bien', '0035_comisionagente'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoComision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modo_pago', models.IntegerField(choices=[(1, 'Contado'), (2, 'Crédito directo'), (4, 'Contado a crédito')], default=1, verbose_name='Modo de pago')),
                ('precio_final', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio final')),
                ('enganche', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Enganche')),
                ('fecha_confirma_pago_adicional', models.DateField(blank=True, null=True, verbose_name='Fecha confirmado')),
                ('fecha_contrato', models.DateField(blank=True, null=True, verbose_name='Fecha de contrato')),
                ('comsion', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Comisión')),
                ('importe', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Importe comisión')),
                ('estatus_pago', models.IntegerField(choices=[(False, 'No'), (True, 'Si')], default=False, verbose_name='Pagado')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('observacion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Observación')),
                ('bien_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bien.lote', verbose_name='Bien_pag_com')),
                ('empleado_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleado.empleado', verbose_name='Empleado_pag_com')),
            ],
            options={
                'verbose_name': 'Pago Comisiones',
                'verbose_name_plural': 'Pago comisión',
                'db_table': 'PagoComision',
                'ordering': ['empleado_pago', '-fecha_contrato'],
                'unique_together': {('bien_pago',)},
            },
            bases=(models.Model, django.contrib.auth.mixins.PermissionRequiredMixin),
        ),
    ]
