# Generated by Django 3.2.4 on 2022-07-29 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bien', '0036_pagocomision'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comisionagente',
            old_name='comsion',
            new_name='comision',
        ),
    ]
