# Generated by Django 3.2.4 on 2022-07-31 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bien', '0037_rename_comsion_comisionagente_comision'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagocomision',
            options={'ordering': ['empleado_pago', '-fecha_contrato'], 'verbose_name': 'Pago comisión', 'verbose_name_plural': 'Pago comisiones'},
        ),
        migrations.AddField(
            model_name='pagocomision',
            name='fecha_pago_comision',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha pago comisión'),
        ),
    ]
