# Generated by Django 3.2.4 on 2022-08-01 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bien', '0039_alter_proyecto_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagocomision',
            name='estatus_pago',
        ),
        migrations.AddField(
            model_name='pagocomision',
            name='comsion_director',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Comisión director'),
        ),
        migrations.AddField(
            model_name='pagocomision',
            name='comsion_publicidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Comisión publicidad'),
        ),
        migrations.AddField(
            model_name='pagocomision',
            name='estatus_pago_comision',
            field=models.IntegerField(choices=[(False, 'No'), (True, 'Si')], default=False, verbose_name='Estatus comisión aasesor'),
        ),
        migrations.AddField(
            model_name='pagocomision',
            name='estatus_pago_director',
            field=models.IntegerField(choices=[(False, 'No'), (True, 'Si')], default=False, verbose_name='Estatus comisión director'),
        ),
        migrations.AddField(
            model_name='pagocomision',
            name='estatus_pago_publicidad',
            field=models.IntegerField(choices=[(False, 'No'), (True, 'Si')], default=False, verbose_name='Estatus comisión publicidad'),
        ),
        migrations.AddField(
            model_name='pagocomision',
            name='fecha_pago_comision_director',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha pago comisión director'),
        ),
        migrations.AddField(
            model_name='pagocomision',
            name='fecha_pago_comision_publicidad',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha pago comisión publicidad'),
        ),
        migrations.AddField(
            model_name='pagocomision',
            name='importe_director',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Importe comisión director'),
        ),
        migrations.AddField(
            model_name='pagocomision',
            name='importe_publicidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Importe comisión publicidad'),
        ),
        migrations.AlterField(
            model_name='pagocomision',
            name='comsion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Comisión asesor'),
        ),
        migrations.AlterField(
            model_name='pagocomision',
            name='fecha_pago_comision',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha pago comisión asesor'),
        ),
        migrations.AlterField(
            model_name='pagocomision',
            name='importe',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Importe comisión asesor'),
        ),
    ]
