# Generated by Django 3.2.4 on 2022-08-01 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bien', '0040_auto_20220801_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagocomision',
            name='estatus_pago_comision',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Si')], default=False, verbose_name='Estatus comisión aasesor'),
        ),
        migrations.AlterField(
            model_name='pagocomision',
            name='estatus_pago_director',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Si')], default=False, verbose_name='Estatus comisión director'),
        ),
        migrations.AlterField(
            model_name='pagocomision',
            name='estatus_pago_publicidad',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Si')], default=False, verbose_name='Estatus comisión publicidad'),
        ),
    ]
