# Generated by Django 3.2.4 on 2022-08-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bien', '0041_auto_20220801_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagocomision',
            name='folio_comision_asesor',
            field=models.IntegerField(default=0, verbose_name='Folio de pago comisión asesor'),
        ),
        migrations.AddField(
            model_name='pagocomision',
            name='folio_comision_director',
            field=models.IntegerField(default=0, verbose_name='Folio de pago comisión director'),
        ),
        migrations.AddField(
            model_name='pagocomision',
            name='folio_comision_publicidad',
            field=models.IntegerField(default=0, verbose_name='Folio de pago comisión publicidad'),
        ),
    ]
