# Generated by Django 3.2.4 on 2022-08-03 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bien', '0045_pagocomision_proyecto_pago'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagocomision',
            old_name='comsion_director',
            new_name='comsion_gerente',
        ),
        migrations.RenameField(
            model_name='pagocomision',
            old_name='estatus_pago_director',
            new_name='estatus_pago_gerente',
        ),
        migrations.RenameField(
            model_name='pagocomision',
            old_name='fecha_pago_comision',
            new_name='fecha_deposito_comision',
        ),
        migrations.RenameField(
            model_name='pagocomision',
            old_name='fecha_pago_comision_director',
            new_name='fecha_deposito_comision_gerente',
        ),
        migrations.RenameField(
            model_name='pagocomision',
            old_name='fecha_pago_comision_publicidad',
            new_name='fecha_deposito_comision_publicidad',
        ),
        migrations.RenameField(
            model_name='pagocomision',
            old_name='folio_comision_director',
            new_name='folio_comision_gerente',
        ),
        migrations.RenameField(
            model_name='pagocomision',
            old_name='importe_director',
            new_name='importe_gerente',
        ),
        migrations.AddField(
            model_name='pagocomision',
            name='comprobante_asesor_deposito',
            field=models.ImageField(blank=True, null=True, upload_to='comAsesor'),
        ),
        migrations.AddField(
            model_name='pagocomision',
            name='comprobante_gerente_deposito',
            field=models.ImageField(blank=True, null=True, upload_to='comGerente'),
        ),
        migrations.AddField(
            model_name='pagocomision',
            name='comprobante_publicidad_deposito',
            field=models.ImageField(blank=True, null=True, upload_to='comPublicidad'),
        ),
        migrations.AddField(
            model_name='pagocomision',
            name='estatus_comision',
            field=models.IntegerField(choices=[(0, 'Pendiente'), (1, 'Confirmada'), (2, 'Pagada')], default=0, verbose_name='Estatus pago comisión periodo'),
        ),
        migrations.AddField(
            model_name='pagocomision',
            name='recibo_asesor_firmado',
            field=models.ImageField(blank=True, null=True, upload_to='comAsesor'),
        ),
        migrations.AddField(
            model_name='pagocomision',
            name='recibo_gerente_firmado',
            field=models.ImageField(blank=True, null=True, upload_to='comGerente'),
        ),
        migrations.AddField(
            model_name='pagocomision',
            name='recibo_publicidad_firmado',
            field=models.ImageField(blank=True, null=True, upload_to='comPublicidad'),
        ),
        migrations.AlterField(
            model_name='pagocomision',
            name='estatus_pago_publicidad',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Si')], default=False, verbose_name='Estatus comisión director'),
        ),
    ]
