# Generated by Django 3.2.4 on 2022-08-03 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bien', '0046_auto_20220803_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagocomision',
            name='fecha_periodo',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha periodo de pago'),
        ),
        migrations.AlterField(
            model_name='pagocomision',
            name='estatus_comision',
            field=models.IntegerField(choices=[(0, 'Pendiente'), (1, 'VoBo'), (2, 'Pagada')], default=0, verbose_name='Estatus pago comisión periodo'),
        ),
    ]
