# Generated by Django 3.2.4 on 2022-08-08 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bien', '0050_auto_20220808_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacionamiento',
            name='compartido',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Si')], default=False, verbose_name='Compartido'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='comision_pagada',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Si')], default=False, verbose_name='Comision pagada'),
        ),
    ]
