# Generated by Django 3.2.4 on 2022-08-08 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bien', '0051_auto_20220808_0056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lote',
            options={'ordering': ['proyecto', 'lote'], 'permissions': (('nuvole_ver', 'Nuvole ver bienes'), ('nuvole_add', 'Nuvole agregar bien'), ('nuvole_chag', 'Nuvole cambiar bien'), ('nuvole_reservar', 'Nuvole reservar bien'), ('toscana_ver', 'Toscana ver bienes'), ('toscana_add', 'Toscana agregar bien'), ('toscana_chag', 'Toscana cambiar bien'), ('toscana_reservar', 'Toscana reservar bien'), ('local_punta_o_ver', 'Punta O local ver bienes'), ('local_punta_o_add', 'Punta O local agregar bien'), ('local_punta_o_chag', 'Punta O local cambiar bien'), ('local_punta_o_reservar', 'Punta O local reservar bien'), ('consul_punta_o_ver', 'Punta O consult ver bienes'), ('consul_punta_o_add', 'Punta O consult agregar bien'), ('consul_punta_o_chag', 'Punta O consult cambiar bien'), ('consul_punta_o_reservar', 'Punta O consult reservar bien'), ('torre_vento_ver', 'Torre Vento ver bienes'), ('torre_vento_add', 'Torre Vento agregar bien'), ('torre_vento_chag', 'Torre Vento cambiar bien'), ('torre_vento_reservar', 'Torre Vento reservar bien bien'), ('porto_santo_ver', 'Fracción 34 ver bienes'), ('porto_santo_add', 'Fracción 34 agregar bien'), ('porto_santo_chag', 'Fracción 34 cambiar bien'), ('porto_santo_reservar', 'Fracción 34 reservar bien'), ('vivienda_nuvole_ver', 'Nuvole viviendas ver bienes'), ('vivienda_nuvole_add', 'Nuvole viviendas agregar bien'), ('vivienda_nuvole_chag', ' Nuvole viviendas cambiar bien'), ('vivienda_nuvole_reservar', 'Nuvole viviendas reservar bien'), ('monte_cristalo_ver', 'Monte cristalo ver bienes'), ('monte_cristalo_add', 'Monte cristalo agregar bien'), ('monte_cristalo_chag', 'Monte cristalo cambiar bien'), ('monte_cristalo_reservar', 'Monte cristalo reservar bien'), ('condom_multiple_ver', 'Condominio Múltiple ver bienes'), ('condom_multiple_add', 'Condominio Múltiple agregar bien'), ('condom_multiple_chag', 'Condominio Múltiple cambiar bien'), ('condom_multiple_reservar', 'Condominio Múltiple reservar bien')), 'verbose_name': 'Lote', 'verbose_name_plural': 'Lotes'},
        ),
        migrations.AlterModelOptions(
            name='proyecto',
            options={'ordering': ['id'], 'permissions': (('nuvole_acceso', 'Nuvole Acceso'), ('toscana_acceso', 'Toscana Acceso'), ('local_punta_o_acceso', 'Local Punta O Acceso'), ('consul_punta_o_acceso', 'Consultorio Punta O Acceso'), ('torre_vento_acceso', 'Torre Vento Acceso'), ('porto_santo_acceso', 'Porto santo Acceso'), ('vivienda_nuvole_acceso', 'Vivienda Nuvole Acceso'), ('monte_cristalo_acceso', 'Monte cristalo Acceso'), ('condom_multiple_acceso', 'Condominio Múltiple Acceso'), ('comision_proyectos', 'Comisiones por proyecto')), 'verbose_name': 'Proyecto', 'verbose_name_plural': 'Proyectos'},
        ),
    ]
