# Generated by Django 3.2.4 on 2022-08-10 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bien', '0055_auto_20220810_0011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lote',
            options={'ordering': ['proyecto', 'lote'], 'permissions': (('nuvole_ver', 'Nuvole ver bienes'), ('nuvole_add', 'Nuvole agregar bien'), ('nuvole_chag', 'Nuvole cambiar bien'), ('nuvole_reservar', 'Nuvole reservar bien'), ('toscana_ver', 'Toscana ver bienes'), ('toscana_add', 'Toscana agregar bien'), ('toscana_chag', 'Toscana cambiar bien'), ('toscana_reservar', 'Toscana reservar bien'), ('local_punta_o_ver', 'Punta O local ver bienes'), ('local_punta_o_add', 'Punta O local agregar bien'), ('local_punta_o_chag', 'Punta O local cambiar bien'), ('local_punta_o_reservar', 'Punta O local reservar bien'), ('consul_punta_o_ver', 'Punta O consult ver bienes'), ('consul_punta_o_add', 'Punta O consult agregar bien'), ('consul_punta_o_chag', 'Punta O consult cambiar bien'), ('consul_punta_o_reservar', 'Punta O consult reservar bien'), ('torre_vento_ver', 'Torre Vento ver bienes'), ('torre_vento_add', 'Torre Vento agregar bien'), ('torre_vento_chag', 'Torre Vento cambiar bien'), ('torre_vento_reservar', 'Torre Vento reservar bien bien'), ('porto_santo_ver', 'Porto Santo ver bienes'), ('porto_santo_add', 'Porto Santo agregar bien'), ('porto_santo_chag', 'Porto Santo cambiar bien'), ('porto_santo_reservar', 'Porto Santo reservar bien'), ('vivienda_nuvole_ver', 'Nuvole viviendas ver bienes'), ('vivienda_nuvole_add', 'Nuvole viviendas agregar bien'), ('vivienda_nuvole_chag', ' Nuvole viviendas cambiar bien'), ('vivienda_nuvole_reservar', 'Nuvole viviendas reservar bien'), ('monte_cristallo_ver', 'Monte cristallo ver bienes'), ('monte_cristallo_add', 'Monte cristallo agregar bien'), ('monte_cristallo_chag', 'Monte cristallo cambiar bien'), ('monte_cristallo_reservar', 'Monte cristallo reservar bien'), ('condom_multiple_ver', 'Condominio Múltiple ver bienes'), ('condom_multiple_add', 'Condominio Múltiple agregar bien'), ('condom_multiple_chag', 'Condominio Múltiple cambiar bien'), ('condom_multiple_reservar', 'Condominio Múltiple reservar bien')), 'verbose_name': 'Lote', 'verbose_name_plural': 'Lotes'},
        ),
    ]
