# Generated by Django 3.2.4 on 2022-08-13 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bien', '0057_alter_lote_comision_pagada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='comision_pagada',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Si')], default='0', verbose_name='Comision pagada'),
        ),
    ]
