# Generated by Django 4.0.4 on 2022-08-26 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bien', '0059_lote_precio_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='tipo_lote',
            field=models.IntegerField(choices=[(1, 'Regular'), (0, 'Irregular')], default=1, verbose_name='Tipo de lote'),
        ),
    ]
