# Generated by Django 4.0.4 on 2022-08-26 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bien', '0060_alter_lote_tipo_lote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='comision_pagada',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Si')], default=0, verbose_name='Comision pagada'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='esquina',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Si')], default=0, verbose_name='Esquina'),
        ),
    ]
