# Generated by Django 4.0.4 on 2022-08-26 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bien', '0061_alter_lote_comision_pagada_alter_lote_esquina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='fase',
            field=models.SmallIntegerField(choices=[(1, 'Uno'), (2, 'Dos'), (3, 'Tres')], default=1, verbose_name='Fase'),
        ),
    ]
