# Generated by Django 4.0.4 on 2022-08-26 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bien', '0062_alter_lote_fase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='fase',
            field=models.SmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], default=1, verbose_name='Fase'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Area'),
        ),
    ]
