# Generated by Django 4.0.4 on 2022-08-26 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bien', '0063_alter_lote_fase_alter_lote_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='fase',
            field=models.SmallIntegerField(choices=[(0, ''), (1, '1'), (2, '2'), (3, '3')], default=1, verbose_name='Fase'),
        ),
    ]
