# Generated by Django 4.0.4 on 2022-08-26 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bien', '0064_alter_lote_fase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='altura',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Altura'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='fase',
            field=models.SmallIntegerField(choices=[(0, ''), (1, '1'), (2, '2'), (3, '3')], default=0, verbose_name='Fase'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='gran_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total gral.'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='precio_terraza',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio terraza'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='precio_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio total'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='precio_x_mt_t',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio por m² terraza'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='terraza',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Terraza m²'),
        ),
    ]
