# Generated by Django 4.0.4 on 2022-08-27 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bien', '0065_alter_lote_altura_alter_lote_fase_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lote',
            unique_together={('proyecto', 'fase', 'manzana', 'lote')},
        ),
    ]
