# Generated by Django 4.0.4 on 2022-08-27 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bien', '0066_alter_lote_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='manzana',
            field=models.SmallIntegerField(default=0, verbose_name='Manzana'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='nivel',
            field=models.SmallIntegerField(default=0, verbose_name='Nivel'),
        ),
    ]
