# Generated by Django 4.0.4 on 2022-08-27 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bien', '0068_alter_lote_estacionamientos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='fecha_alta',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='usuario_ins',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='usuario_mod',
        ),
        migrations.AlterField(
            model_name='estacionamiento',
            name='compartido',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Si')], default=0, verbose_name='Compartido'),
        ),
        migrations.AlterField(
            model_name='estacionamiento',
            name='coordenadas',
            field=models.CharField(default=' ', max_length=255, verbose_name='Coordenas'),
        ),
        migrations.AlterField(
            model_name='estacionamiento',
            name='fondo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2, verbose_name='fondo'),
        ),
        migrations.AlterField(
            model_name='estacionamiento',
            name='frente',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2, verbose_name='frente'),
        ),
        migrations.AlterField(
            model_name='estacionamiento',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizadcurrento'),
        ),
        migrations.AlterField(
            model_name='estacionamiento',
            name='numero',
            field=models.CharField(default=' ', max_length=10, verbose_name='lugar'),
        ),
        migrations.AlterField(
            model_name='estacionamiento',
            name='posicion_circulo_x',
            field=models.IntegerField(default=0, verbose_name='Posición X circulo'),
        ),
        migrations.AlterField(
            model_name='estacionamiento',
            name='posicion_circulo_y',
            field=models.IntegerField(default=0, verbose_name='Posición Y circulo'),
        ),
        migrations.AlterField(
            model_name='estacionamiento',
            name='posicion_texto_x',
            field=models.IntegerField(default=0, verbose_name='Posición X mts'),
        ),
        migrations.AlterField(
            model_name='estacionamiento',
            name='posicion_texto_y',
            field=models.IntegerField(default=0, verbose_name='Posición Y mts'),
        ),
        migrations.AlterField(
            model_name='estacionamiento',
            name='posicion_x',
            field=models.IntegerField(default=0, verbose_name='Posición X numero'),
        ),
        migrations.AlterField(
            model_name='estacionamiento',
            name='posicion_y',
            field=models.IntegerField(default=0, verbose_name='Posición Y numero'),
        ),
        migrations.AlterField(
            model_name='estacionamiento',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2, verbose_name='total'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='nom_proy',
            field=models.CharField(default=' ', max_length=30, verbose_name='Abrev Proyecto'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='singular',
            field=models.CharField(default=' ', max_length=50, verbose_name='Proyecto en sigular'),
        ),
    ]
