# Generated by Django 4.0.4 on 2022-08-27 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bien', '0069_remove_proyecto_fecha_alta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacionamiento',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bien.proyecto', verbose_name='Proyecto_estac'),
        ),
    ]
