# Generated by Django 4.0.4 on 2022-08-27 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bien', '0070_estacionamiento_proyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagocomision',
            name='enganche',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Enganche'),
        ),
    ]
