# Generated by Django 4.0.4 on 2022-09-06 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0019_rename_subidpersdonal_empleado_subidpersonal'),
        ('bien', '0073_rename_estatus_pago_comision_pagocomision_estatus_pago_asesor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagocomision',
            options={'ordering': ['asesor_pago', '-fecha_contrato'], 'verbose_name': 'Pago comisión', 'verbose_name_plural': 'Pago comisiones'},
        ),
        migrations.RemoveField(
            model_name='pagocomision',
            name='empleado_pago',
        ),
        migrations.AddField(
            model_name='pagocomision',
            name='asesor_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Empleado_pag_com', to='empleado.empleado', verbose_name='Empleado_pag_com'),
        ),
        migrations.AddField(
            model_name='pagocomision',
            name='gerente_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Gerente_pag_com', to='empleado.empleado', verbose_name='Gerente_pag_com'),
        ),
    ]
