# Generated by Django 4.0.4 on 2022-09-06 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0019_rename_subidpersdonal_empleado_subidpersonal'),
        ('bien', '0074_alter_pagocomision_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagocomision',
            name='asesor_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empleado.empleado', verbose_name='Empleado_pag_com'),
        ),
    ]
