# Generated by Django 4.0.4 on 2022-09-27 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bien', '0075_alter_pagocomision_asesor_pago'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagocomision',
            options={'ordering': ['asesor_pago', '-fecha_contrato'], 'permissions': (('nuvole_imprime_comprob_comision', 'Nuvole imprime comprobante comisión'), ('toscana_imprime_comprob_comision', 'Toscana imprime comprobante comisión'), ('local_punta_o_imprime_comprob_comision', 'Local Punta O imprime comprobante comisión'), ('consul_punta_o_imprime_comprob_comision', 'Consultorio Punta O imprime comprobante comisión'), ('torre_vento_imprime_comprob_comision', 'Torre Vento imprime comprobante comisión'), ('porto_santo_imprime_comprob_comision', 'Porto santo imprime comprobante comisión'), ('vivienda_nuvole_imprime_comprob_comision', 'Vivienda Nuvole imprime comprobante comisión'), ('monte_cristallo_imprime_comprob_comision', 'Monte cristallo imprime comprobante comisión'), ('condom_multiple_imprime_comprob_comision', 'Condominio Múltiple imprime comprobante comisión')), 'verbose_name': 'Pago comisión', 'verbose_name_plural': 'Pago comisiones'},
        ),
        migrations.AlterField(
            model_name='pagocomision',
            name='estatus_comision',
            field=models.IntegerField(choices=[(0, 'Nueva'), (1, 'Depósito pendiente'), (2, 'Recibos pendientes'), (3, 'Terminada')], default=0, verbose_name='Estatus pago comisión periodo'),
        ),
    ]
