# Generated by Django 4.0.4 on 2022-10-04 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bien', '0076_alter_pagocomision_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagocomision',
            name='estatus_comision',
            field=models.IntegerField(choices=[(0, 'Nueva'), (1, 'Depósito pendiente'), (2, 'Impresión de recibos'), (3, 'Terminada')], default=0, verbose_name='Estatus pago comisión periodo'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_alta',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha alta proyecto'),
        ),
    ]
