# Generated by Django 4.0.4 on 2023-02-01 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bien', '0077_alter_pagocomision_estatus_comision_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='estatus_lote',
            field=models.IntegerField(choices=[(1, 'Disponible'), (2, 'Apartado'), (3, 'Vendido'), (4, 'Reservado'), (9, 'Eliminado')], default=1, verbose_name='Estatus'),
        ),
    ]
