# Generated by Django 4.0.4 on 2023-02-18 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bien', '0078_alter_lote_estatus_lote'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='piso_default',
            field=models.IntegerField(default=0, verbose_name='Piso default'),
        ),
    ]
