# Generated by Django 4.0.4 on 2023-07-02 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bien', '0081_alter_lote_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='area',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Area'),
        ),
    ]
