# Generated by Django 4.0.4 on 2023-07-02 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bien', '0082_lote_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='bano',
            field=models.IntegerField(choices=[(0, '1 Baño'), (1, '1 1/2 Baños'), (2, '2 Baños'), (3, '2 1/2 Baños'), (4, '3 Baños'), (5, '3 1/2 Baños'), (6, '4 Baños')], default=0, verbose_name='Baño(s)'),
        ),
        migrations.AddField(
            model_name='lote',
            name='habitacion',
            field=models.IntegerField(default=0, verbose_name='Habitaciones'),
        ),
    ]
