# Generated by Django 4.0.4 on 2023-07-02 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bien', '0083_lote_bano_lote_habitacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lote',
            options={'ordering': ['proyecto', 'gpo_lote', 'nivel', 'lote'], 'permissions': (('nuvole_ver', 'Nuvole ver bienes'), ('nuvole_add', 'Nuvole agregar bien'), ('nuvole_chag', 'Nuvole cambiar bien'), ('nuvole_reservar', 'Nuvole reservar bien'), ('toscana_ver', 'Toscana ver bienes'), ('toscana_add', 'Toscana agregar bien'), ('toscana_chag', 'Toscana cambiar bien'), ('toscana_reservar', 'Toscana reservar bien'), ('local_punta_o_ver', 'Punta O local ver bienes'), ('local_punta_o_add', 'Punta O local agregar bien'), ('local_punta_o_chag', 'Punta O local cambiar bien'), ('local_punta_o_reservar', 'Punta O local reservar bien'), ('consul_punta_o_ver', 'Punta O consult ver bienes'), ('consul_punta_o_add', 'Punta O consult agregar bien'), ('consul_punta_o_chag', 'Punta O consult cambiar bien'), ('consul_punta_o_reservar', 'Punta O consult reservar bien'), ('torre_vento_ver', 'Torre Vento ver bienes'), ('torre_vento_add', 'Torre Vento agregar bien'), ('torre_vento_chag', 'Torre Vento cambiar bien'), ('torre_vento_reservar', 'Torre Vento reservar bien bien'), ('porto_santo_ver', 'Porto Santo ver bienes'), ('porto_santo_add', 'Porto Santo agregar bien'), ('porto_santo_chag', 'Porto Santo cambiar bien'), ('porto_santo_reservar', 'Porto Santo reservar bien'), ('vivienda_nuvole_ver', 'Nuvole viviendas ver bienes'), ('vivienda_nuvole_add', 'Nuvole viviendas agregar bien'), ('vivienda_nuvole_chag', ' Nuvole viviendas cambiar bien'), ('vivienda_nuvole_reservar', 'Nuvole viviendas reservar bien'), ('monte_cristallo_ver', 'Monte cristallo ver bienes'), ('monte_cristallo_add', 'Monte cristallo agregar bien'), ('monte_cristallo_chag', 'Monte cristallo cambiar bien'), ('monte_cristallo_reservar', 'Monte cristallo reservar bien'), ('condom_multiple_ver', 'Condominio Múltiple ver bienes'), ('condom_multiple_add', 'Condominio Múltiple agregar bien'), ('condom_multiple_chag', 'Condominio Múltiple cambiar bien'), ('condom_multiple_reservar', 'Condominio Múltiple reservar bien'), ('nuvole2_ver', 'Nuvole 2 ver bienes'), ('nuvole2_add', 'Nuvole 2 agregar bien'), ('nuvole2_chag', 'Nuvole 2 cambiar bien'), ('nuvole2_reservar', 'Nuvole 2 reservar bien')), 'verbose_name': 'Lote', 'verbose_name_plural': 'Lotes'},
        ),
        migrations.AlterModelOptions(
            name='pagocomision',
            options={'ordering': ['asesor_pago', '-fecha_contrato'], 'permissions': (('nuvole_imprime_comprob_comision', 'Nuvole imprime comprobante comisión'), ('toscana_imprime_comprob_comision', 'Toscana imprime comprobante comisión'), ('local_punta_o_imprime_comprob_comision', 'Local Punta O imprime comprobante comisión'), ('consul_punta_o_imprime_comprob_comision', 'Consultorio Punta O imprime comprobante comisión'), ('torre_vento_imprime_comprob_comision', 'Torre Vento imprime comprobante comisión'), ('porto_santo_imprime_comprob_comision', 'Porto santo imprime comprobante comisión'), ('vivienda_nuvole_imprime_comprob_comision', 'Vivienda Nuvole imprime comprobante comisión'), ('monte_cristallo_imprime_comprob_comision', 'Monte cristallo imprime comprobante comisión'), ('condom_multiple_imprime_comprob_comision', 'Condominio Múltiple imprime comprobante comisión'), ('nuvole2_imprime_comprob_comision', 'Nuvole 2 imprime comprobante comisión')), 'verbose_name': 'Pago comisión', 'verbose_name_plural': 'Pago comisiones'},
        ),
        migrations.AlterModelOptions(
            name='proyecto',
            options={'ordering': ['id'], 'permissions': (('nuvole_acceso', 'Nuvole Acceso'), ('toscana_acceso', 'Toscana Acceso'), ('local_punta_o_acceso', 'Local Punta O Acceso'), ('consul_punta_o_acceso', 'Consultorio Punta O Acceso'), ('torre_vento_acceso', 'Torre Vento Acceso'), ('porto_santo_acceso', 'Porto santo Acceso'), ('vivienda_nuvole_acceso', 'Vivienda Nuvole Acceso'), ('monte_cristallo_acceso', 'Monte cristallo Acceso'), ('condom_multiple_acceso', 'Condominio Múltiple Acceso'), ('nuvole2_acceso', 'Nuvole 2 Acceso'), ('comision_proyectos', 'Comisiones por proyecto')), 'verbose_name': 'Proyecto', 'verbose_name_plural': 'Proyectos'},
        ),
    ]
