# Generated by Django 4.0.4 on 2023-07-07 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bien', '0084_alter_lote_options_alter_pagocomision_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='tipo_proyecto',
            field=models.IntegerField(choices=[(1, 'Lotes'), (2, 'Locales comerciales'), (3, 'Vivienda horizontal'), (4, 'Vivienda vertical'), (5, 'Consultorios')], default=1, verbose_name='Tipo de proyecto'),
        ),
    ]
