# Generated by Django 4.0.4 on 2022-05-31 20:59

from django.conf import settings
import django.contrib.auth.mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('paterno', models.CharField(max_length=30, verbose_name='Paterno')),
                ('materno', models.CharField(blank=True, max_length=30, null=True, verbose_name='Materno')),
                ('rfc', models.CharField(blank=True, max_length=20, null=True, verbose_name='R.F.C.')),
                ('curp', models.CharField(blank=True, max_length=18, null=True, verbose_name='CURP')),
                ('fecha_nac', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name='Género')),
                ('estado_civil', models.IntegerField(blank=True, choices=[(1, 'Soltero'), (2, 'Casado'), (3, 'Unión libre'), (4, 'Divorciado')], null=True, verbose_name='Estado civil')),
                ('numero_seguro_social', models.CharField(blank=True, max_length=12, null=True, verbose_name='Número de seguro social')),
                ('cuenta_banco', models.CharField(blank=True, max_length=18, null=True, verbose_name='Cuenta nómina')),
                ('tipo_pago', models.CharField(choices=[('H', 'Horas'), ('D', 'Diario'), ('S', 'Semanal'), ('Q', 'Quincenal'), ('M', 'Mensual')], default='Q', max_length=1, verbose_name='Pago')),
                ('calle_num', models.CharField(blank=True, max_length=250, null=True, verbose_name='Dirección')),
                ('colonia', models.CharField(blank=True, max_length=200, null=True, verbose_name='Colonia')),
                ('municipio', models.CharField(blank=True, max_length=150, null=True, verbose_name='Municipio')),
                ('estado', models.IntegerField(blank=True, choices=[(0, 'Sin Estado'), (1, 'Aguascalientes'), (2, 'Baja California'), (3, 'Baja California Sur'), (4, 'Campeche'), (5, 'Coahuila'), (6, 'Colima'), (7, 'Chiapas'), (8, 'Chihuahua'), (9, 'Ciudad de México'), (10, 'Durango'), (11, 'Guanajuato'), (12, 'Guerrero'), (13, 'Hidalgo'), (14, 'Jalisco'), (15, 'México'), (16, 'Michoacán'), (17, 'Morelos'), (18, 'Nayarit'), (19, 'Nuevo León'), (20, 'Oaxaca'), (21, 'Puebla'), (22, 'Querétaro'), (23, 'Quintana Roo'), (24, 'San Luis Potosí'), (25, 'Sinaloa'), (26, 'Sonora'), (27, 'Tabasco'), (28, 'Tamaulipas'), (29, 'Tlaxcala'), (30, 'Veracruz'), (31, 'Yucatán'), (32, 'Zacatecas')], default=0, null=True, verbose_name='Estado')),
                ('codpos', models.CharField(blank=True, max_length=5, null=True, verbose_name='Código Postal')),
                ('telefono_fijo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefono fijo')),
                ('celular', models.CharField(blank=True, max_length=10, null=True, verbose_name='Celular')),
                ('correo', models.EmailField(blank=True, max_length=180, null=True, verbose_name='Correo')),
                ('tipo_empleado', models.CharField(choices=[('I', 'Interno'), ('E', 'Externo')], default='E', max_length=1, verbose_name='Interno/Externo')),
                ('area_operativa', models.SmallIntegerField(choices=[(1, 'Dirección'), (2, 'Contabilidad'), (3, 'Recursos Humanos'), (4, 'Finanzas'), (5, 'Asesoria'), (6, 'Operación'), (7, 'Desarrollo Urbano')], default=5, verbose_name='Área operativa')),
                ('asigna_solicitud', models.BooleanField(blank=True, choices=[(False, 'NO'), (True, 'Si')], default=False, null=True, verbose_name='Asigna solicitudes')),
                ('estatus_empleado', models.IntegerField(choices=[(1, 'Activo'), (2, 'Baja')], default=1, verbose_name='Activo')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='personal')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('banco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.banco', verbose_name='Banco cta. depositar')),
                ('subidPersdonal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Personal', to='empleado.empleado', verbose_name='Asignado a')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='em_auth_user', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('usuario_ins', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='em_user_ins', to='empleado.empleado', verbose_name='Usuario insertó')),
                ('usuario_mod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='em_user_mod', to='empleado.empleado', verbose_name='Usuario modificó')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Personal',
                'db_table': 'Empleado',
                'ordering': ['paterno', 'materno', 'nombre'],
                'unique_together': {('rfc',), ('curp',), ('numero_seguro_social',)},
            },
            bases=(models.Model, django.contrib.auth.mixins.PermissionRequiredMixin),
        ),
    ]
