# Generated by Django 4.0.4 on 2022-06-06 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='asigna_solicitud',
            field=models.BooleanField(blank=True, choices=[(False, 'No'), (True, 'Si')], default=False, null=True, verbose_name='Asigna solicitudes'),
        ),
    ]
