# Generated by Django 3.2.4 on 2022-07-31 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0002_alter_empleado_asigna_solicitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='puesto',
            field=models.SmallIntegerField(choices=[(1, 'Dirección General'), (2, 'Finanzas'), (3, 'Asesoria de Ventas')], default=1, verbose_name='Puesto'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='area_operativa',
            field=models.SmallIntegerField(choices=[(1, 'Dirección General'), (2, 'Finanzas'), (3, 'Asesoria de Ventas')], default=5, verbose_name='Área operativa'),
        ),
    ]
