# Generated by Django 3.2.4 on 2022-07-31 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0004_alter_empleado_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='area_operativa',
            field=models.SmallIntegerField(choices=[(1, 'Dirección General'), (2, 'Finanzas'), (3, 'Asesoria de Ventas')], default=3, verbose_name='Área operativa'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='puesto',
            field=models.SmallIntegerField(choices=[(1, 'Dirección General'), (2, 'Finanzas'), (3, 'Asesoria de Ventas')], default=3, verbose_name='Puesto'),
        ),
    ]
