# Generated by Django 3.2.4 on 2022-07-31 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0006_alter_empleado_puesto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='puesto',
            field=models.SmallIntegerField(choices=[(1, 'Asesor'), (2, 'Gerente de asesores'), (3, 'Director General'), (4, 'Personal de finanzas')], default=1, verbose_name='Puesto'),
        ),
    ]
