# Generated by Django 3.2.4 on 2022-07-31 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0007_alter_empleado_puesto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'ordering': ['paterno', 'materno', 'nombre'], 'permissions': (('comisiones_asesor', 'Comisiones por asesor'),), 'verbose_name': 'Empleado', 'verbose_name_plural': 'Personal'},
        ),
    ]
