# Generated by Django 3.2.4 on 2022-07-31 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0008_alter_empleado_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='estatus_empleado',
            field=models.IntegerField(choices=[(1, 'Activo'), (2, 'Baja')], default=1, verbose_name='Estatus'),
        ),
    ]
