# Generated by Django 3.2.4 on 2022-08-08 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0010_alter_empleado_asigna_solicitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='asigna_solicitud',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Si')], default=1, null=True, verbose_name='Asigna solicitudes'),
        ),
    ]
