# Generated by Django 3.2.4 on 2022-08-08 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0011_alter_empleado_asigna_solicitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='asigna_solicitud',
            field=models.IntegerField(blank=True, choices=[(False, 'No'), (True, 'Si')], default=0, null=True, verbose_name='Asigna solicitudes'),
        ),
    ]
