# Generated by Django 3.2.4 on 2022-08-22 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0013_alter_empleado_asigna_solicitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='estado_civil',
            field=models.IntegerField(choices=[(1, 'Soltero'), (2, 'Casado'), (3, 'Unión libre'), (4, 'Divorciado')], default=1, verbose_name='Estado civil'),
        ),
    ]
