# Generated by Django 4.0.4 on 2022-08-28 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0015_alter_empleado_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='usuario_ins',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='usuario_mod',
        ),
    ]
