# Generated by Django 4.0.4 on 2022-08-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0016_remove_empleado_usuario_ins_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='asigna_solicitud',
            field=models.SmallIntegerField(choices=[(0, 'No'), (1, 'Si')], default=0, verbose_name='Asigna solicitudes'),
        ),
    ]
