# Generated by Django 4.0.4 on 2022-09-03 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0017_alter_empleado_asigna_solicitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='area_operativa',
            field=models.SmallIntegerField(choices=[(1, 'Dirección General'), (2, 'Finanzas'), (3, 'Ventas')], default=3, verbose_name='Área operativa'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='celular',
            field=models.CharField(default=' ', max_length=20, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='puesto',
            field=models.SmallIntegerField(choices=[(1, 'Asesor'), (2, 'Gerente de ventas'), (3, 'Director General'), (4, 'Personal de finanzas'), (5, 'Director comercial')], default=1, verbose_name='Puesto'),
        ),
    ]
