# Generated by Django 4.0.4 on 2022-09-06 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0018_alter_empleado_area_operativa_alter_empleado_celular_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='subidPersdonal',
            new_name='subidPersonal',
        ),
    ]
