# Generated by Django 4.0.4 on 2022-09-28 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0019_rename_subidpersdonal_empleado_subidpersonal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'ordering': ['paterno', 'materno', 'nombre'], 'permissions': (('comisiones_asesor', 'Comisiones por asesor'),), 'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
    ]
